### ISSUE TITLE
Crashes in Minecraft 1.19

### ISSUE THREAD

**Issue by 1-1037** [henkelmax/gravestone#102]
**Bug description**
Minecraft crashes before even getting to the main menu on the latest 1.19 Forge version, even if it is the only mod installed.

**Steps to reproduce the issue**
1. Install latest 1.19 forge version (41.0.98)
2. Install GraveStone Mod
3. Launch Minecraft
4. Game crash

**Expected behavior**
Minecraft actually loads

**Log files**
Crash Log: [crash-2022-07-14_02.54.08-fml.txt](https://github.com/henkelmax/gravestone/files/9109751/crash-2022-07-14_02.54.08-fml.txt)
Latest Log: [latest.log](https://github.com/henkelmax/gravestone/files/9109759/latest.log)

**Versions**
Minecraft: 1.19
Forge: 41.0.98
Mod: gravestone-1.19-1.0.1

**Other mods**
None

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/77138306/178931717-bea6a966-8f66-4a3b-a443-d64f061024cc.png)

**Comment by henkelmax** [comment]
Forge had a breaking change. If you update forge, you also need to update the mod. This is already fixed in 1.0.2
