### ISSUE TITLE
Failed to load correctly

### ISSUE THREAD

**Issue by Elektroi1** [henkelmax/gravestone#105]
[crash-2022-07-16_17.38.15-fml.txt](https://github.com/henkelmax/gravestone/files/9126653/crash-2022-07-16_17.38.15-fml.txt)

Uploaded crash report. Failed due to Block Entity

**Comment by henkelmax** [comment]
Please properly fill out the bug template.

**Comment by Elektroi1** [comment]
**Bug description**
A clear and concise description of what the bug is.

**Steps to reproduce the issue**
1. Click on play on minecraft with Forge
2. Crashes occur during start up

**Expected behavior**
game to start without crash 

**Log files**
Crash Log file attached in original post

**Versions**
- Minecraft version 1.19
- Forge version: 1.19 - 41.0.99
- Mod version 1.19 - 1.0.1 

**Other mods**
TerraBlender-forge-1.19-2.0.0.112.jar
TravelersBackpack-1.19-8.0.4.jar

**Screenshots (Optional)**
NONE

**Comment by henkelmax** [comment]
Forge had a breaking change in 41.0.94 The latest gravestone version already updated to that Forge version.
