### ISSUE TITLE
gravestone-common.toml Not Generating

### ISSUE THREAD

**Issue by Omikron-Delta** [henkelmax/gravestone#106]
**Bug description**
Config files are not generating on new instances.

**Steps to reproduce the issue**
1) Create a new Minecraft instance and install Forge + Gravestone
2) gravestone-common.toml will not generate on launching

**Expected behavior**
The gravestone-common.toml file generates.

**Log files**
No relevant logs

**Versions**
- Minecraft 1.18.2
- Forge 40.1.60
- Mod 1.18.2-1.0.2

**Comment by Omikron-Delta** [comment]
Log upon generating new instance:
https://gist.github.com/Omikron-Delta/46e65f18b5bf662c05c63484fe7e301e

**Comment by henkelmax** [comment]
There is no `gravestone-common.toml`
