### ISSUE TITLE
a possible bug a friend of mine found

### ISSUE THREAD

**Issue by kuba26038** [henkelmax/gravestone#108]
as they said, 
"The screen with coal and dirt and crap, that's what was in my grave when i collected it, clutter i got getting back to my grave the first time. Then there's pics taken of the grave's items according to obituary, and where the grave should be according to obituary, which is not where it is. i have thoroughly searched the area, dug around a bit right now, i've broken every grave, even ones that are a bit farther away, nothing in them. i have genuinely no clue what happened, i just know i died at the same exact time i broke it and my items were gone"
![2022-07-24_10 55 35](https://user-images.githubusercontent.com/81324988/180658811-42988cef-1492-44c4-b787-cc405e441287.png)
![2022-07-24_10 50 42](https://user-images.githubusercontent.com/81324988/180658821-f5301e2a-12da-47dc-8bf3-99c9a4efcd51.png)
![2022-07-24_10 56 15](https://user-images.githubusercontent.com/81324988/180658833-2571d3db-53c0-4667-8024-6ac33742acae.png)

i'm not sure what happened here exactly, so if you'd help me with maybe recreating this i'd be really thankful

**Comment by henkelmax** [comment]
What is your actual question now?
I'm assuming how to get back the items that were lost?
There is a command to restore the items of a specific death. Just use the grave ID provided in the obituary.

**Comment by kuba26038** [comment]
no, my question was if what happened here is a bug and if so, how would i go about with reproducing it? i really don't want for stuff like that to happen, you know?

**Comment by henkelmax** [comment]
You didn't provide me any information I would need to tell you if its a bug. I don't even know on which version you are.

**Comment by kuba26038** [comment]
i don't really have that info so i guess this isn't really a problem
