### ISSUE TITLE
[1.16.3] Obituary not always getting removed upon grave retrieval.

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/gravestone#11]
**Bug description**
When you pickup / retrieve your grave the Obituary Note doesn't always get removed from the inventory. Even though the config option is set to do that.

**Steps to reproduce the issue**
1. Enable 'Remove_Obituary' in the config: 
![image](https://user-images.githubusercontent.com/26634554/96106304-5a448a00-0edb-11eb-95bf-8b01c33823b0.png)
2. Join the world.
3. Use the kill command.
4. Retrieve grave.
5. Obituary Note still in inventory instead of being removed.

**Expected behavior**
Obituary Note getting removed from the inventory as described by the config.

**Log files** - _(I don't see anything related to gravestones in the logs but here you go.)_
[latest.log](https://github.com/henkelmax/gravestone/files/5383872/latest.log)

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.19
- Mod version: [2.0.0](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/files/3080677)

**Other mods**
Same issue without mods aswell but here's the mods:
https://gist.github.com/Gbergz/ae7d468f6652b87f0035b2e76a8f2db5

**Screenshots / GIF**
https://gyazo.com/0467170cf43acb17f039ec28c7bc2fd6

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
It should be up on curse in a few minutes.

**Comment by Gbergz** [comment]
Seems to be fixed. 
Thank you!

**Comment by henkelmax** [comment]
No problem!
