### ISSUE TITLE
Obituary and gravestone not spawning in Multiplayer server

### ISSUE THREAD

**Issue by DiZeroX** [henkelmax/gravestone#114]
**Bug description**
On (Magma) Forge 1.18.2 server, the GraveStone mod does not spawn obituaries or gravestones. The only mod on the server is GraveStone and Forge, so there is no conflict with other 3rd party mods. It works correctly in single player world.

**Steps to reproduce the issue**
1. Go to https://magmafoundation.org/
2. Download 1.18.2 server JAR
3. Create and run `start.bat` with relevant details (example: `java -jar -Xmx[INSERT X GB HERE]G Magma-1.18.2-40.1.73-cca106b5-server.jar`)
4. Add GraveStone mod jar (1.18.2 1.0.1) to `mods` directory
5. Restart server to init config files
6. Create a Vanilla 1.18.2 Forge world in GDLauncher
7. Add GraveStone mod jar (1.18.2 1.0.1) to `mods` (client) directory
8. Create new single player world
9. Die and obituary/grave works correctly
10. Join the server from steps 1-5 
11. Die and obituary/grave does not work

**Expected behavior**
Obituary to be in inventory when respawned and gravestone placed at the spot of death with items.

**Log files**
Server debug.log:
[debug.log](https://github.com/henkelmax/gravestone/files/9463333/debug.log)

**Versions**
- Minecraft version: 1.18.2
- Forge version: 40.1.74
- Mod version: 1.18.2 1.0.1

**Other mods**
Forge
(no other mods installed)

**Comment by henkelmax** [comment]
Hybrid servers are not supported.
