### ISSUE TITLE
Restore command not working (1.19.2)

### ISSUE THREAD

**Issue by zPanic** [henkelmax/gravestone#115]
**Bug description**
Restore command not working in minecraft 1.19.2

**Steps to reproduce the issue**
1. Sneak + rightclick obituary or make a /restore command
2. Execute the command
3. Get the message "Too many arguments. Usage: /restore [snapshot]

**Expected behavior**
Adding or replacing an inventory from a gravestone

**Versions**
- 1.19.2
- 1.19.2, 43.1.16
- 1.19.2-1.0.0

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/190484812-05ee066f-9107-4b3f-8ba9-ee08bca29cb5.png)

Works perfectly fine.

**Comment by jinkhya** [comment]
I'm having the same issue on andromeda automation modpack in 1.18.2.
![image](https://user-images.githubusercontent.com/10158963/191072302-8e1cd759-9fb4-43fd-8e6b-b174bebe3d75.png)
![image](https://user-images.githubusercontent.com/10158963/191072378-8bb4a633-7b43-402c-87a1-c3b96484923d.png)
![image](https://user-images.githubusercontent.com/10158963/191072395-2e1b7a35-101b-48ee-a114-874486163725.png)

**Comment by henkelmax** [comment]
That looks like a command conflict to me

**Comment by silentnyte** [comment]
I have run into this also. Is it possible to change the command to something other than restore, like grave-restore?

**Comment by henkelmax** [comment]
This has already been implemented.
