### ISSUE TITLE
World Freezing after death

### ISSUE THREAD

**Issue by Catomax262** [henkelmax/gravestone#117]
**Bug description**
For some reason after dying or holding the obituary the world freezes in place, making the chunks invisible and the player too, locking the player in the air
**Steps to reproduce the issue**
1. Die
2. Check, hold obituary or destroy grave
3. See error

**Expected behavior**
 Not freezing my world and letting me grab my death items.

**Log files**
https://mclo.gs/O8xBX5a

**Versions**
- 1.18.2
- 40.1.69
- 1.0.1

**Other mods**
https://pastebin.com/8bXgxav8

**Screenshots (Optional)**
n/a

**Comment by henkelmax** [comment]
Does this also happen without any other mods installed?

**Comment by henkelmax** [comment]
Closed due to inactivity
