### ISSUE TITLE
inventorio compatibility

### ISSUE THREAD

**Issue by UdoMorgenstern** [henkelmax/gravestone#118]
**Is your feature request related to a problem? Please describe.**
When dying none of the items from the slots added by inventorio are added to the graves. they are just deleted from the world

**Describe the solution you'd like**
Best case scenario would be if all items from the slots (toolbar, actionbar, deep pocket slots) would be added to the grave as well as put pack into the inventory when breaking/using the grave.

**Describe alternatives you've considered**
Just recovering the items would be fine regardless of re-equipting them (similar to curio slots).

**Additional context**
Link to mod: https://www.curseforge.com/minecraft/mc-mods/inventorio-forge
Link to mod git: https://github.com/Lizard-Of-Oz/Inventorio 

```
repositories {
  maven {
    url "https://cursemaven.com"
    content {
      includeGroup "curse.maven"
    }
  }
}

dependencies {
  modCompileOnly "curse.maven:inventorio-491073:3963530" //Fabric
  modCompileOnly "curse.maven:inventorio-497122:3963529" //Forge
}
```

**Comment by polenball** [comment]
same request here
