### ISSUE TITLE
Epic fights mod issue

### ISSUE THREAD

**Issue by foxy0352** [henkelmax/gravestone#122]
Epic fights mod keeps crashing my game. when i go to fight a mob or animal while in combat mode my game crashes as soon as i hit them my game just closes

no other mods installed

crash report:
[crash-2022-12-10_13.52.31-server.txt](https://github.com/henkelmax/gravestone/files/10201033/crash-2022-12-10_13.52.31-server.txt)

**Comment by foxy0352** [comment]
it also said "The game crashed whilst ticking entity"

**Comment by henkelmax** [comment]
Duplicate of #68
