### ISSUE TITLE
Support for Curios

### ISSUE THREAD

**Issue by darchitectlp** [henkelmax/gravestone#126]
Every major modpack includes Curios... but whenever I pick up my corpse, the curios don't go back to where they belong. Any chance you'd add? Really, this is one of my favorite grave mods. When I died in the ocean, and went back to find my corpse floating on the water I almost fell out of my chair laughing! Great mod!

**Comment by henkelmax** [comment]
Duplicate of #119

**Comment by darchitectlp** [comment]
Ok. Will find a different mod, then. Thanks.

**Comment by SonicTheHedgehog58987276** [comment]
<img width="960" alt="Screenshot 2023-06-30 155354" src="https://github.com/henkelmax/gravestone/assets/115895321/59499378-1502-435a-9356-17e30b82cd5f">
