### ISSUE TITLE
Restore Command Capabilities

### ISSUE THREAD

**Issue by firemaster1294** [henkelmax/gravestone#128]
I just went through the long process of trying to locate where a player’s inventory is stored after death so I could try to restore their inventory. This took way too long to figure out.

I would like to request, at a minimum: documentation stating that world/deaths contains player death info categorized by player UUID. Additionally, it could be nice if /restore would automatically pull from the possible options and sort them by day and time (also visible to the command user). As an admin this would make life so much easier.

**Comment by henkelmax** [comment]
The death IDs are shown in the obituary if you have extended item tooltips on.

**Comment by firemaster1294** [comment]
Here’s the issue…my player threw their obituary into lava not realizing this was a functionality of this. So unless I have a way of getting the ID of a destroyed item, I can’t do anything :/

**Comment by henkelmax** [comment]
You can look at the last modified date of the death files.
