### ISSUE TITLE
Grave is destroyed by explosion or deleted by battle tower

### ISSUE THREAD

**Issue by TeslaC0il** [henkelmax/gravestone#129]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I beat a battle tower, it started to blow up top down, died of fall damage trying to run down the stairs, gravestone was there for a minute, but disappeared when I wasn’t looking

**Steps to reproduce the issue**
1. Beat land battle tower
2. Die during self destruct sequence
3. Watch gravestone

**Expected behavior**
It not blowing up or being deleted?

**Log files**

**Versions**
- Minecraft version 1.18.2
- Forge version most recent
- Mod version most recent for 1.18.2

**Other mods**
A list of the other mods that were installed when this problem occurred.
Speshel’s magic and sorcery modpack, plus GraveStone, ParCool, as well as MnA and GeckoLib being updated

**Comment by henkelmax** [comment]
This is most likely an issue with the mod that deleted the grave. We can't do anything about that if they are not respecting block tags.

**Comment by TeslaC0il** [comment]
Well that’s not good :(
