### ISSUE TITLE
[1.16.3] Add support for Curious Mod.

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/gravestone#13]
**Feature request**
Items in the Curious item slots doesn't stay in their slots upon grave retrieval.

**Describe the solution you'd like**
Let the equipped items in the Curious slots stay in their respective slots when you retrieve the grave. Instead of appearing in normal inventory.

**Additional context**
It's just annoying to re-equip every single Curious item upon every death.

Kind regards,
**-** Gbergz

**Comment by henkelmax** [comment]
I won't add specific compatibilities for other mods. This just adds more complexity and dependencies, that would delay updating to newer versions.

**Comment by Gbergz** [comment]
Gotcha, thanks for the quick answer though!

**Comment by henkelmax** [comment]
No problem!
