### ISSUE TITLE
Items gone from grabestine glitch

### ISSUE THREAD

**Issue by leobestgamer** [henkelmax/gravestone#136]
I was trying to get my stuff and died while doing so , as I was going to get the gravestone ( i saw the gravestone) i broke it and as soon as i broke it a skeleton killed me , while going back to the place the grave was gone and the obituary was no where to be found. I think this happened because the new gravestone that happened overwrited the old one , And I dont know how to get the exact stuff back , i have admin priviliege and the deaths recorded on my server

How to repeat the bug : break a gravestone and as soon as you break it make something kill you

What was expected : my items from the older graveyard 

The version is 1.16.5

**Comment by henkelmax** [comment]
1. Please fill out the bug template.
2. The gravestone is not able to replace itself. its only able to replace blocks like grass or liquids.
3. This version is no longer supported.

**Comment by leobestgamer** [comment]
> 1. Please fill out the bug template.
> 2. The gravestone is not able to replace itself. its only able to replace blocks like grass or liquids.
> 3. This version is no longer supported.

Is there anything i can do to retreive my stuff tho? i have all the deaths recorded but when I open the file its all in question marks and there isnt any id i could copy to restore anything , could you help me with this?

**Comment by henkelmax** [comment]
Use the `/restore` command

**Comment by leobestgamer** [comment]
> Use the `/restore` command

i can use it but i need the UUID and i dont have that , how could i get it?

**Comment by henkelmax** [comment]
The UUID is shown in the obituary item if you have advanced tooltips on. Alternatively you can get the UUID from the death file name. You can sort it by date to find the correct one.

**Comment by leobestgamer** [comment]
the thing is i dont have the obituary itself, and I cant take anything from the death files because its .mce, im gonna send you a death file to know what im talking about.

**Comment by leobestgamer** [comment]
got it , thank you very much.
