### ISSUE TITLE
[1.20.1] Client crash CME- 

### ISSUE THREAD

**Issue by ProsperCraft** [henkelmax/gravestone#138]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I teleported to a player that was getting killed over and over, and on load in my client crashed.

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Not CME

**Log files**
(https://gist.githubusercontent.com/ProsperCraft/82ed463d80df044d6a22082d558b6f76/raw/08110d2e63c705f408c2d078e505e392dc433b46/gistfile1.txt)

**Versions**
- Minecraft version 1.21.1
- Forge version forge/1.20.1-47.0.19
- Mod version gravestone-1.20.1-1.0.3

**Other mods**
TownCraft for 1.12.1 version 0.1

**Comment by henkelmax** [comment]
Does this happen without any other mods?
