### ISSUE TITLE
[1.16.3] Ice and Fire conflicts with Gravestones- Grave doesn't spawn sometimes. Not even the obituary.

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/gravestone#14]
**Bug description**
When you die the gravestone sometimes doesn't spawn at all, and sometimes a message in chat displaying that you died won't even appear. And the obituary isn't given out.

**Steps to reproduce the issue**
1. Install Gravestones along with Ice and fire (and citadel requirement)
2. Start client, join world/server. (im on a server trying this)
3. Kill someone, a player.
4. Grave doesn't spawn.
5. Profit.

**Expected behavior**
That the grave & obituary spawns with no issues.

**Log files**
[latest.log](https://github.com/henkelmax/gravestone/files/5405286/latest.log)

**Most noticable thing in the logs:**
https://hastebin.com/furibisuxu.properties

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.21
- Mod version: [gravestone-1.16.3-2.0.3](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/files/3085284)

**Other mods** (reproducable with only gravestones, iceandfire+citadel)
https://gist.github.com/Gbergz/5a9c61e47de1c0b6daba9d88d69ba22f

**Screenshots GIF**
https://gyazo.com/83f771287b29591ad8a0e8aefb46a5dc

**Additional Information**:
This happens on a clean instance with only Gravestones mod, Citadel & Ice and Fire.

**Comment by henkelmax** [comment]
This seems to be an issue of the Ice and Fire mod, since the exception in the logs occurred in their code.
Please open a new issue on their issue tracker.
