### ISSUE TITLE
Cannot find the config file

### ISSUE THREAD

**Issue by BobDonner** [henkelmax/gravestone#140]
I am using the version 1.19.4-1.0.3 with Forge version forge 45.1.0 and OptiFine_1.19.4_HD_U_I4.jar. I have multiple versions of Forge installed so the only config file that I can find for Gravestone is located in: C:\Users\me\AppData\Roaming\.minecraft\versions\Forge 1.19.4\config\gravestone-client.toml

There are only two options inside the file: one, to show the skull, and two, the color of the grave text.

I cannot find a config folder for gravestone anywhere on my pc. My real issue here is the marker that is displayed at the site of my deaths. A bright green X marks the spot of my deaths and there is a beacon shooting way up into the air. This is a great feature to have since it helps locate the gravesite but I died 6 times within 50 blocks of my spawn point (a raid gone horribly wrong lol) and now these markers are persistent in my world. Uninstalling Gravestone does not remove the markers. Thanks for your help resolving this as if I cannot remove them I will restart the world with another gravestone mod as there are several others available for 1.19.4. I would prefer to use yours but I cannot stand the persistent markers so close to my base.

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/gravestone/faq

**Comment by BobDonner** [comment]
> https://modrepo.de/minecraft/gravestone/faq

Thanks for your help, I did not know that I had to look in the closed issues to see your response. 

Yes it was a minimap mod (Journeymap) that was causing the issue. I had to remove the 'deaths' folder to keep the markers from appearing. Yay! I can keep using your terrific mod and no longer have to see the markers.
