### ISSUE TITLE
Items lost if dying in water

### ISSUE THREAD

**Issue by DRYN07** [henkelmax/gravestone#142]
Is it normal that if I die in water, all my items are lost and the gravestone does not work? I find it, but it is just an item without my head on it.

**Comment by henkelmax** [comment]
Did you actually break the block and nothing came out?

**Comment by varruzen** [comment]
Same thing happened to me, block appears as item entity floating without name or skull. you can pick it up and place it down, still without face or name. and when you break it with anything it breaks as the item like you used silk touch on it.

**Comment by DRYN07** [comment]
@henkelmax, just like @varruzen said :/

It happened to my friends as well, only when we died in water.

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/gravestone/assets/13237524/6b1c018c-4625-4577-8e71-e84313d90bfc)
Works perfectly fine.
