### ISSUE TITLE
Underwater Death

### ISSUE THREAD

**Issue by Xispas01** [henkelmax/gravestone#143]
**Bug description**
When a player dies underwater, since the grave can be destroyed by water. All items are lost

**Steps to reproduce the issue**
1. Die underwater (if you are in multiplayer the player that doesn't die can see how the tomb is generated and then broken by water)

**Expected behavior**
The grave becomes waterlogged or doesn't break with water

**Log files**
Since the grave generates as expected no abnormal log files are present

**Versions**
- Minecraft version 1.20.1
- Fabric version 0.14.21
- Mod version 1.15

**Other mods**
No other mods create the error

**Comment by henkelmax** [comment]
Tested it and works perfectly fine.

**Comment by henkelmax** [comment]
And this is a Forge mod, not a Fabric mod @Xispas01

**Comment by pedr69** [comment]
happens to me too, the grave spawns as an item and floats to the surface. placing it down and breaking will just drop the grave item again
i am also running this in a fabric pack

**Comment by henkelmax** [comment]
This is NOT a fabric mod. You are on the wrong issue tracker!
@pedr69

**Comment by pedr69** [comment]
i know, and i'm wondering why it works on fabric in the first place
also thinking which of the following would be the least bad to implement
* proper fabric port
* if fabric is present send "not a fabric mod, expect shit to break" to chat
* if fabric is present crash

**Comment by henkelmax** [comment]
You are on the wrong issue page. You are referring to another mod that's for Fabric.

**Comment by pedr69** [comment]
i'll be damned, you're right
the right one is https://github.com/Geometrically/Gravestones
