### ISSUE TITLE
No death.dat file is generated some times

### ISSUE THREAD

**Issue by Rakotonndra** [henkelmax/gravestone#147]
**Bug description**
Graves and obituaries are not generated when players die. No death.dat file is generated either.

**Steps to reproduce the issue**
Just getting killed. It sucks that this is kind of a random issue that I'm struggling to track down.

**Expected behavior**
I expect to get my grave spawned (which happens most of the time), but sometimes that doesn't happen. Obituaries do not generate either and no death.dat file is generated in the deaths folder, which is an unwanted behaviour

**Log files**
I'm not really sure which logs would be useful. I am open to share any file if you could please tell me which files.

**Versions**
- Minecraft version: 1.19.2
- Forge version: 43.2.0
- Mod version: 1.0.1

**Other mods**
https://gist.github.com/Rakotonndra/c6f146d0f3de3f754bf9f75d05b82160

**Comment by henkelmax** [comment]
I can't help you without logs.

**Comment by Rakotonndra** [comment]
Which logs do you need? Where do i find the file?

**Comment by henkelmax** [comment]
`logs/latest.log`

**Comment by henkelmax** [comment]
Closed due to inactivity
