### ISSUE TITLE
Mod does not work at all

### ISSUE THREAD

**Issue by bloxanne123** [henkelmax/gravestone#15]
Hi, I use 1.16.2 to play minecraft on. When I die, no grave is _ever_ placed. I do not know why. MC launches fine with the mod, but  Mod Menu does not show it, but for some reason MultiMC says it is enabled. https://paste.ee/p/D6X40 This is the link to the log. I have no idea why it is not enabled. Please help me!

**Comment by henkelmax** [comment]
This mod is not a fabric mod. You have to use Forge.
