### ISSUE TITLE
Grave generates above death location in next available free space, potentially all the way on the surface if killed in confined area

### ISSUE THREAD

**Issue by Voltem0** [henkelmax/gravestone#150]
**Bug description**
When Dying underground, in some cases the gravestone will instead appear on the surface, needing a dedicated search to find it rather than just going to the spot where the player died. The moratorium shows the death coordinates, but not the coordinates where the gravestone spawned making the recovery very cumbersome.

**Steps to reproduce the issue**
1) Go underground into a tight corridor (1 block wide, 2 blocks high) with no adjacent caves or hollow spaces. above spaces and caves are fine so long as there is at least 5 blocks to showcase the issue. 
2) die, either by mob or /kill command
3) done

**Expected behavior**
The mod generates the gravestone above the actual death location in the next available space. this can be either a random cave or on the surface, even if the player died a hundred blocks underground.

**log files**
https://gist.github.com/Voltem0/986def8ce00990163f54eb4c108c666d

**Versions**
- Minecraft: 1.20.1
- Forge: 47
- Mod version: 1.05

**Other mods**
Now i noticed this issue as part of a modpack, but it occurs consistently with only the gravestones mod alone.

**Comment by Voltem0** [comment]
"works as intended"? how the heck is this an intended feature?
If i die while underground i at least know how i got there, if the gravestone spawns on the surface in a forest i have to check underground first, then discover it is not there only to have to search for it above ground! the whole point of the mod is to leave a grave marker on the location where the player died, not miles above it!

**Comment by henkelmax** [comment]
From https://legacy.curseforge.com/minecraft/mc-mods/gravestone-mod:

![image](https://github.com/henkelmax/gravestone/assets/13237524/62a9275e-c96f-4ba1-99c9-5271c9506f8a)


It always has been like that. It is clearly stated on the mod page that it works like this.

**Comment by Voltem0** [comment]
I assumed this line was for if you are trapped in gravel and there are no free spaces on your location, not that the grave always needed a free block above the character's head. After all, the grave does not generate above the characters head-level usually but on the ground.
Neither are 2-block tall strip-mines something unusual in minecraft.

But alright, bit confused as to why this is the intended way but fair enough.
