### ISSUE TITLE
Gravestone Missing - does not spawn upon death

### ISSUE THREAD

**Issue by Deafpie** [henkelmax/gravestone#153]
**Bug description**
After a few deaths, gravestones stop spawning. There isn't much to say aside from this. Obituaries work great for recovering lost items, but the mod has become useless without working gravestones

**Steps to reproduce the issue**
Restart Server, works a few times after then stops spawning on death

**Expected behavior**
The Gravestone to spawn on death

**Log files**
(https://gist.github.com/Deafpie/81c013e76579f132be67e98a4aae905f)

**Versions**
- Minecraft version - 1.20.1
- Mod loader - Forge
- Mod loader version - 47.2.0
- Mod version - gravestone-1.20.1-1.0.5.jar

**Other mods**
11/12/2023  07:08 PM         2,806,951 AgeOfWeapons-Reforged-1.20.x-(v.1.2.3).jar
11/12/2023  08:10 AM           567,579 architectury-9.1.12-forge.jar
11/12/2023  05:41 PM           621,359 artifacts-forge-9.2.0.jar
11/12/2023  05:38 PM           196,447 bellsandwhistles-0.4.3-1.20.x.jar
11/12/2023  05:31 PM        21,800,460 BiomesOPlenty-1.20.1-18.0.0.592.jar
11/12/2023  05:37 PM           139,102 botarium-forge-1.20.1-2.2.1.jar
11/12/2023  08:10 AM         1,168,375 cloth-config-11.1.106-forge.jar
11/12/2023  08:09 AM            20,299 Clumps-forge-1.20.1-12.0.0.3.jar
11/12/2023  05:30 PM        14,964,127 create-1.20.1-0.5.1.f.jar
11/12/2023  05:37 PM         2,123,089 create-confectionery1.20.1_v1.1.0.jar
11/12/2023  05:37 PM         1,151,274 create-stuff-additions1.20.1_v2.0.4a.jar
11/12/2023  05:37 PM         1,119,629 createaddition-1.20.1-1.1.1.jar
11/12/2023  05:38 PM           183,884 createbb-1.20.1-3.1.2.jar
11/12/2023  05:38 PM         1,657,082 createdieselgenerators-1.20.1-1.2d.jar
11/12/2023  05:37 PM           286,745 createoreexcavation-1.20-1.4.1.jar
11/12/2023  05:37 PM           281,281 createsifter-1.20.1-1.8.1.e-22.jar
11/12/2023  05:38 PM           205,630 create_mechanical_extruder-1.20.1-1.5.7.e-22.jar
11/12/2023  05:37 PM         1,014,347 create_misc_and_things_ 1.20.1_4.0A.jar
11/12/2023  05:38 PM            89,302 create_recycle_1.0.2_forge_1.20.1.jar
11/12/2023  08:10 AM           307,735 curios-forge-5.4.2+1.20.1.jar
11/12/2023  08:10 AM           578,959 Decorative Blocks-forge-1.20.1-4.0.2.jar
11/12/2023  05:56 PM            40,535 DistantFriends-1.20.1-0.5.3.jar
11/12/2023  08:10 AM         8,579,488 DungeonsArise-1.20.1-2.1.57-release.jar
11/12/2023  08:10 AM           157,405 explorify-v1.3.0-mc1.20.jar
11/12/2023  08:11 AM         2,898,860 FarmersDelight-1.20.1-1.2.3.jar
11/12/2023  08:10 AM           286,410 flib-1.20.1-0.0.11.jar
11/12/2023  08:10 AM         2,915,980 friendsandfoes-forge-mc1.20.1-1.9.8.jar
11/12/2023  08:10 AM           887,115 ftb-chunks-forge-2001.2.3.jar
11/12/2023  05:30 PM           155,787 ftb-essentials-forge-2001.2.1.jar
11/12/2023  08:10 AM           612,384 ftb-library-forge-2001.1.3.jar
11/12/2023  08:10 AM         1,139,210 ftb-quests-forge-2001.1.7.jar
11/12/2023  05:30 PM            85,218 ftb-ranks-forge-2001.1.3.jar
11/12/2023  08:10 AM           240,019 ftb-teams-forge-2001.1.4.jar
11/12/2023  05:30 PM            97,029 ftb-ultimine-forge-2001.1.2.jar
11/12/2023  05:30 PM            11,076 FTBQuestsOptimizer-forge-1.1.3-1.20.1.jar
11/12/2023  08:11 AM           984,073 geckolib-forge-1.20.1-4.2.4.jar
11/13/2023  02:48 PM           251,557 gravestone-1.20.1-1.0.5.jar
11/12/2023  08:11 AM           198,605 guardvillagers-1.20.1-1.6.3.jar
11/12/2023  08:11 AM         2,330,173 IllagerInvasion-v8.0.3-1.20.1-Forge.jar
11/12/2023  05:38 PM           414,215 interiors-0.5-30+mc1.20.1.jar
11/12/2023  08:09 AM           110,191 item-filters-forge-2001.1.0-build.59.jar
11/12/2023  05:40 PM         1,047,301 jackseconomy-1.1.2B.jar
11/12/2023  08:10 AM         1,112,891 jei-1.20.1-forge-15.2.0.27.jar
11/12/2023  08:10 AM         7,137,741 journeymap-1.20.1-5.9.16-forge.jar
11/12/2023  08:11 AM         7,606,810 kotlinforforge-4.5.0-all.jar
11/12/2023  05:36 PM           800,766 l2library-2.4.21.jar
11/13/2023  12:21 PM           275,128 lootr-1.20-0.7.30.73.jar
11/12/2023  05:33 PM           399,366 mes-1.3-1.20-forge.jar
11/12/2023  05:30 PM         1,072,511 moonlight-1.20-2.8.60-forge.jar
11/12/2023  06:46 PM           188,456 moremobvariants-forge+1.20-1.2.2.jar
11/12/2023  05:33 PM         1,338,583 mvs-4.1.1-1.20-forge.jar
11/13/2023  12:12 PM         1,260,235 pmmo-1.20.1-1.2.9.jar
11/12/2023  06:58 PM           168,816 pmmo_skill_books-1.0.0-1.20.1.jar
11/12/2023  05:43 PM           712,374 PuzzlesLib-v8.0.19-1.20.1-Forge.jar
11/12/2023  06:55 PM           101,352 randommobsizes-forge-1.20.1-1.3.jar
11/12/2023  05:27 PM         1,226,854 recruits-1.20.1-1.10.10.jar
11/12/2023  05:41 PM            21,792 Renforced_Brass_Armor_1.20.1.jar
11/12/2023  06:58 PM            29,530 shadowizardlib-1.20.1-1.0.7.jar
11/12/2023  07:09 PM            55,913 shw-forge-1.0.0.jar
11/12/2023  06:58 PM           244,403 skillcloaks-1.20.1-1.2.2.jar
11/12/2023  05:37 PM           224,151 sliceanddice-forge-3.2.0.jar
11/12/2023  05:30 PM           794,051 sophisticatedbackpacks-1.20.1-3.18.66.941.jar
11/12/2023  05:30 PM         1,021,005 sophisticatedcore-1.20.1-0.5.105.485.jar
11/12/2023  05:30 PM        14,866,594 supplementaries-1.20-2.6.26.jar
11/12/2023  06:56 PM           467,590 TaxCastlePillager+M.1.20.1+ForM.1.0.0.jar
11/12/2023  08:11 AM           105,368 TerraBlender-forge-1.20.1-3.0.0.169.jar
11/12/2023  05:27 PM             7,029 villagerdrops-forge-1.20.1-v1.3.0.jar
11/12/2023  05:41 PM            56,156 villagertools-1.20.1-1.0.3.jar
11/12/2023  08:10 AM           244,668 villagesandpillages-forge-mc1.20.1-1.0.0.jar
11/12/2023  05:27 PM         1,159,491 workers-1.20.1-1.7.5.jar
11/13/2023  11:25 AM         5,825,402 worldedit-mod-7.2.15.jar
11/12/2023  08:10 AM           346,402 YungsApi-1.20-Forge-4.0.2.jar
11/12/2023  07:07 PM         2,439,913 [1.20.1-forge]-Epic-Knights-8.8.jar

**Screenshots (Optional)**
Screenshots of the issue. NA

**Comment by henkelmax** [comment]
I was not able to reproduce this with your steps.
Please provide better instructions on how to reliably reproduce this issue.
You might also want to try this without any other mods installed.
