### ISSUE TITLE
Silverfish can destroy the grave

### ISSUE THREAD

**Issue by DenisNovac** [henkelmax/gravestone#154]
**Bug description**
My friend died to the silverfishes and then they somehow removed the grave.

**Steps to reproduce the issue**
1. Die to silverfish
2. Wait for them to hide into blocks
3. Check the gravestone
4. Maybe won't work first try

**Expected behavior**
Gravestones should be unbreakable

**Versions**
- Minecraft 1.20.1
- Forge 47.2.0
- Mod 1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Comment by henkelmax** [comment]
Is this reproducible reliably?
If yes, please send me your logs like stated in the issue template.
And also try if this happens without any other mods.

**Comment by adedw** [comment]
This wasn't a silverfish, I died from warden, again without a grave. Empty logs, only died message.
