### ISSUE TITLE
documentation on how to configure grave restore. 

### ISSUE THREAD

**Issue by Mitchm0nstr** [henkelmax/gravestone#157]
Hello,
I'm having troubles on my server with restoring a grave. I'm an admin and have both tried typing the command myself, along with shift clicking the Obituary, and it comes up with the Too many arguments prompt. I feel as if I've tried everything that might've been incorrect with the command, but haven't gotten it to work. Extra documentation would be helpful in enabling the use of the /restore command.

**Comment by henkelmax** [comment]
https://github.com/henkelmax/gravestone#recovering-lost-items-1163

If this doesn't work, there is a possibility another mod also registered a /restore command, overriding it.

**Comment by Mitchm0nstr** [comment]
Okay. I appreciate the help... do you know if there is a way to figure out if a mod is using the /restore command? I does pop up with the exact syntax referred to in the post linked. That post is one that I'd found while searching for the correct way to use the command.

**Comment by henkelmax** [comment]
can you show me the exact command you executed?

**Comment by Mitchm0nstr** [comment]
/restore @s 3c90460a-c624-4eeb-b678-31e34d0a14d1 add

Picture attached is error I recieve...
![2023-12-03_15 54 27](https://github.com/henkelmax/gravestone/assets/149990620/9c654e42-1556-4fbf-8040-3dfe78c6e248)

**Comment by henkelmax** [comment]
yeah that command is overridden by another mod. You either need to remove that other mod or you cant use the command.
