### ISSUE TITLE
Loosing item when full inventory

### ISSUE THREAD

**Issue by glea94** [henkelmax/gravestone#158]
**Bug description**
Item dissapear after breaking the grave if the inventory is full when other items are in trinkets (artefact/backpack)

**Steps to reproduce the issue**
1.full inventory and full trinket
2.breaking the grave
3.some items dissapear.

**Expected behavior**
Items in trinket could dissapear due to full inventory, could be a backpack full of items and ressource and also item in trinket.
Expect to see the item on the floor rather than to dissapear as it seems to be vaccumed and deleted.

**Versions**
- 1.20.1
- Forge
- 47.2.17
- 1.0.10

**Other mods**
Sophisticated backpack, trinkets

**Comment by henkelmax** [comment]
The items that don't fit the inventory should be dropped at the spot of the gravestone.

**Comment by henkelmax** [comment]
Closed due to inactivity.

**Comment by glea94** [comment]
Yes i've played yesterday and saw that item where on the ground. Sorry for the late answer.
