### ISSUE TITLE
[1.16.3] Grave doesn't spawn when dying on Vines while sneaking, maybe alot of other blocks too?

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/gravestone#16]
**Bug description**
When dying on a vine the gravestone literally gets placed then erased immediately.

**Steps to reproduce the issue**
1. Stand on a wall with vines while sneaking.
2. Kill player / get killed by something. A mod makes it so you auto crouch in my modpack, but in vanilla you can use a command block and activate it while sneaking to kill yourself.
3. Dead.
4. Grave didn't spawn.

**Expected behavior**
Grave gets placed and doesn't get erased.

**Log files**
Nothing in the logs.

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.25
- Mod version: 2.0.3

**Other mods (Happens without all these mods aswell.)**
https://hatebin.com/hqcosfotyh

**GIF Modded**
https://gyazo.com/219a9cae55a54d7b7fe69ec10a804ade

**GIFs Vanilla w/ only Gravestone mod**
https://gyazo.com/51e058da3c300ebe8ab40048d1a0fd88
https://gyazo.com/5f3a1b8d734a99020403dd7f39f4dc8a

**Comment by henkelmax** [comment]
I'm sorry, but I am not able to reproduce this issue. Can you send me the log files of the server and the client. Please also send me the server config and the client config.

**Comment by Gbergz** [comment]
note that this only occurrs when in survival, non existant while in creative mode. And it does happen on SP & MP.

defaultconfig config: (uploaded as .txt as it .toml wasn't supported.)
[gravestone-server.txt(toml)](https://github.com/henkelmax/gravestone/files/5488534/gravestone-server.txt)

logs:
[latest.log](https://github.com/henkelmax/gravestone/files/5488564/latest.log)

additional gif:
https://gyazo.com/1ab0b9c7e62be0aac1579d2d07f6e39f

**Comment by henkelmax** [comment]
Thanks for providing me this. I found the issue. The sneak pickup caused to transfer the items to the dead player.

**Comment by henkelmax** [comment]
It should be up on curseforge in a few minutes.

**Comment by Gbergz** [comment]
> It should be up on curseforge in a few minutes.

Saw it. Is it possible to get this for 1.16.3 aswell? It's currently what the modpack I have is on.

**Comment by Gbergz** [comment]
nevermind, it is available for 1.16.3 dont mind me.

**Comment by henkelmax** [comment]
I uploaded the 1.16.3 version before 1.16.4. Somehow 1.16.4 got approved earlier :D 
1.16.3 should be up every moment.

![image](https://user-images.githubusercontent.com/13237524/98134283-e0dafe80-1ebe-11eb-9019-fc6c9b797a51.png)

**Comment by Gbergz** [comment]
The issue is indeed fixed. Thank you. :) 👍
