### ISSUE TITLE
died on a dripstone 

### ISSUE THREAD

**Issue by Giakopo** [henkelmax/gravestone#164]
### Bug description

I died from damage from falling onto a dripstone. When I respawn I had no obituary in my inventory, I returned to where I died and there was only the experience and no trace of the tomb. I can't even restore the objects with the /restore command because I don't know the death ID. How can I do?

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.10

### Mod loader and version

Forge 47.2.17

### Steps to reproduce

1. take altitude 
2. fall on a dripstone

### Expected behavior

get my items back

### Log files

https://gist.github.com/Giakopo/0f9cf13a679fd2d72c336387e14e8c06

### Screenshots

![2024-02-26_19 40 55](https://github.com/henkelmax/gravestone/assets/161368302/9e78d8f5-f464-483b-a95c-105332a9bf43)

![Screenshot 2024-02-26 194540](https://github.com/henkelmax/gravestone/assets/161368302/fb734864-cb4f-45c4-bb19-989b280f79b1)

**Comment by henkelmax** [comment]
The error seems to be caused by https://www.curseforge.com/minecraft/mc-mods/v-tweaks
Please remove that mod and check if it still happens.

**Comment by Giakopo** [comment]
Yes I remove the mod and most likely it won't happen again but what about all my items?

**Comment by henkelmax** [comment]
The V Tweaks mod caused a crash which made your death event not being able to be processed. There's nothing that can be done about that.
