### ISSUE TITLE
the grave does not appear and my steuf disappears

### ISSUE THREAD

**Issue by Linkxx08** [henkelmax/gravestone#167]
### Bug description

when I die, the grave does not appear and my items in my inventory remain for around 10 seconds then disappear.the graves appeared before.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.15

### Mod loader and version

Forge 47.2.0 and my serveur in Mohist 1.20.1

### Steps to reproduce

1. install mohist version 1.20.1 on a server
2. install these mods: 
architectury-9.1.12-forge.jar
artifacts-forge-9.2.0.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
citadel-2.4.9-1.20.1.jar
cloth-config-11.1.106-forge.jar
CraftTweaker-forge-1.20.1-14.0.33.jar
curios-forge-5.4.5+1.20.1.jar
FarmersDelight-1.20.1-1.2.3.jar
gravestone-forge-1.20.1-1.0.15.jar
Jade-1.20.1-forge-11.7.1.jar
JadeAddons-1.20.1-forge-5.2.2.jar
jei-1.20.1-forge-15.2.0.27.jar
JeiTweaker-forge-1.20.1-8.0.6.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
L_Enders_Cataclysm-1.90 -1.20.1.jar
lookinsharp-forge-1.20.1-1.0.2.jar
modnametooltip-1.20.1-1.20.0.jar
resourcefullib-forge-1.20.1-2.1.19.jar
sophisticatedbackpacks-1.20.1-3.20.1.1012.jar
sophisticatedcore-1.20.1-0.6.3.553.jar
voicechat-forge-1.20.1-2.4.29.jar
WI-Zoom-1.5-MC1.20.1-Forge.jar
Xaeros_Minimap_23.9.3_Forge_1.20.jar
XaerosWorldMap_1.37.2_Forge_1.20.jar
3. try to die several times

### Expected behavior

when I die a grave appears and I can break it to recover my items

### Log files

https://gist.github.com/Linkxx08/d204a25f231699aef62c581d49529f63

**Comment by henkelmax** [comment]
We don't support hybrid servers.

**Comment by Linkxx08** [comment]
ok but a few weeks ago everything was working fine

**Comment by henkelmax** [comment]
Thats the issue with hybrid servers. They tend to break stuff in very weird and unpredictable ways.
