### ISSUE TITLE
Trinkets API compatibility

### ISSUE THREAD

**Issue by hermengarde** [henkelmax/gravestone#168]
### Bug description

Great mod but feels incomplete on games where Trinkets API is being used as the items on those slots still drop on death. Would appreciate it if a future update allows items in trinket slots to also be saved/re-equipped (or at least placed back in the inventory) when breaking the gravestone.

### Minecraft version

1.19.2

### Mod version

1.19.2

### Mod loader and version

Fabric

### Steps to reproduce

1. Have any mods using Trinkets API
2. Die

### Expected behavior

Upon player death, items equipped to Trinkets slots do not drop separately, Instead, they are also saved in the gravestone.
When the gravestone is broken, these items are placed back in their previous slots like other equipment (or at least get sent into the inventory).

### Log files

https://gist.github.com/hermengarde/77a2452ca37254d3a57acf081bab1210

**Comment by henkelmax** [comment]
If items from that mod get dropped on death, they are not using Forges API correctly. Please report that to their issue tracker.

**Comment by henkelmax** [comment]
Closed due to inactivity.
