### ISSUE TITLE
Mod gives death note but no grave or anything

### ISSUE THREAD

**Issue by tekman123** [henkelmax/gravestone#17]
Bug description
When using newest version of cyclic you can die and lose all items with no grave and no lost of items or death id in your inventory

Steps to reproduce the issue

Die while having the cyclic mod installed

Expected behavior
Grave gets placed and doesn't get erased.

Log files 

(https://github.com/henkelmax/gravestone/files/5507756/latest.log)
Versions

Minecraft version: 1.16.3
Forge version: 34.1.42
Mod version: 2.0.3

Mods installed: 
Cyclic-1.16.3-0.9.1 and gravestones newest version

[latest.log](https://github.com/henkelmax/gravestone/files/5507756/latest.log)

**Comment by henkelmax** [comment]
Please use the provided issue template.

**Comment by henkelmax** [comment]
It's actually a cyclic issue. I made a PR on their repo that fixes it.
