### ISSUE TITLE
No license supplied with the source code.

### ISSUE THREAD

**Issue by DeltaTimo** [henkelmax/gravestone#177]
### Bug description

No license is supplied with the source code, making it difficult to contribute and/or make changes.

### Minecraft version

Any

### Mod version

Any

### Mod loader and version

Any

### Steps to reproduce

1. Clone the repository.
2. Find no `LICENSE` file.

### Expected behavior

Find a LICENSE file in the source tree specifying the license.

### Log files

https://example.com/

**Comment by henkelmax** [comment]
On GitHub, having no license is implicitly considered ad All Rights Reserved.
