### ISSUE TITLE
Error in Server Couldn't load tag gravestone:grave_replaceable....

### ISSUE THREAD

**Issue by ndv01** [henkelmax/gravestone#178]
### Bug description

[Worker-Main-8/ERROR] [minecraft/TagLoader]: Couldn't load tag gravestone:grave_replaceable as it is missing following references:
        minecraft:grass (from mod/gravestone)

### Minecraft version

1.21.1

### Mod version

1.0.21

### Mod loader and version

Neoforge  21.1.23

### Steps to reproduce

while having on the server and launching the server with this mods this error occurs

### Expected behavior

not having an error in the log ?

### Log files

https://gist.github.com/ndv01/2ff4a285bba9e76e40a14bb3e9d70a76

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?

**Comment by ndv01** [comment]
Yes
