### ISSUE TITLE
[1.16.3]Server config not being generated in pack

### ISSUE THREAD

**Issue by bbgott** [henkelmax/gravestone#18]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
When creating a new pack in 1.16.3 only the gravestone-client.toml config file is generated in the config directory.  Doesn't appear to read the gravestone.toml file if created manually

**Steps to reproduce the issue**
1. Create new custom modpack in twitch
2. Add gravestone mod
3. Boot game
4. Check config directory for files to configure

**Expected behavior**
Both gravestone.toml and gravestone-client.toml to be created so I can configure the mod

**Log files**
https://gist.github.com/bbgott/c972ac4e0a5c35645be64e8336e313bb

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.40
- Mod version: 2.0.4

**Other mods**
No other mods installed for test

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
Please read the FAQ, like the issue template says.

**Comment by bbgott** [comment]
I'm sorry for the ticket, I guess I overlooked that question in the FAQ.  I didn't expect the config to be located anywhere besides the config directory
