### ISSUE TITLE
Add a publically available config example

### ISSUE THREAD

**Issue by maxgeraldist** [henkelmax/gravestone#183]
### Bug description

Right now, an example of a config that would mention the names of all of the config variables cannot be found, at least by me. The default file name and directory would also be nice.

### Minecraft version

1.20.1

### Mod version

1.20.1

### Mod loader and version

Forge

### Steps to reproduce

1. Go to the server's files directory, 2. see the config file, 3. Not know how to, e.g. overwrite the default obituary behavior because the variable name is not written anywhere

### Log files

 https://gist.github.com/

**Comment by henkelmax** [comment]
All config options that exist are already present.
