### ISSUE TITLE
Death Waypoint beam does not go away when waypoint deleted

### ISSUE THREAD

**Issue by eractnod** [henkelmax/gravestone#19]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
After dying, a death waypoint is created.  After deleting the waypoint, the white beam stays.  Tried to restart game, but beam is still there.

**Expected behavior**

After deleting waypoint, beam is removed as well.
**Log files**
There are no logs to display this issue.

**Versions**
- Minecraft version 1.16.4
- Forge version 35.0.15
- Mod version 1.0.3

**Other mods**
Started in 1.16.4.  Have all the same mods that I was using in 1.16.3
![2020-11-16_19 22 49](https://user-images.githubusercontent.com/5204558/99323942-2beefd00-2841-11eb-8a7f-eda06b3f9038.png)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Like the bug template says:

> Please read the FAQ before submitting a bug report!
