### ISSUE TITLE
[1.16.4 Bug] The gravestone disappeared.

### ISSUE THREAD

**Issue by ScottCTD** [henkelmax/gravestone#24]
**Bug description**
If a player is killed when he was in a portal and ready for teleporting, the gravestone of that player will disappear in both worlds.

I've tested it already with my friend.

Sorry for troubling you and thanks for providing such a good mod!

**Steps to reproduce the issue**
1. Find a player.
2. Killed that player when in portal like neither portal
3. No gravestone left

**Expected behavior**
No gravestone left

**Log files**
No any erroneous or warning or informational log

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.6
- Mod version 1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
It shouldn't relate to any other mod.

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
Sorry, but I am not able to reproduce this issue. The gravestone appears on top of the portal every time I try it:

![2020-12-01_10 20 14](https://user-images.githubusercontent.com/13237524/100720895-f27ccc80-33be-11eb-8ef8-a1161b9123f3.png)

Have you read the [FAQ](https://modrepo.de/minecraft/gravestone/faq)?

> If you died in a wall, there is a high chance that the gravestone is placed at the next free spot above your death location.

**Comment by ScottCTD** [comment]
Ohhhh my world...
I'm sooo sorry.
I've read the FAQ but I still ignored the top of the portal.
My bad eye my bad  
so sorry for bro
Sorry for consuming your time... Sorry man

**Comment by henkelmax** [comment]
No problem :)
