### ISSUE TITLE
no gravestone/obituary appearing

### ISSUE THREAD

**Issue by zuzzaannaa** [henkelmax/gravestone#25]
I'm on a multiplayer server using Aternos. I downloaded the mod and one of my friends died and the gravestone or obituary is appearing. There is a 'block' there but it's invisible and breaking the blocks around it or trying to destroy it doesn't do anything. Is their stuff gone or is there a way to get it back.

other mods:
collective-1.16.4-1.53.jar

jei-1.16.4-7.6.0.58.jar

oneplayersleeping-1.16.4-0.0.4.jar

treeharvester_1.16.4-2.0.jar

**Comment by henkelmax** [comment]
Please use the provided bug template. Don't forget to send me the logs of your server and your client.
Also please make sure you have the mod installed on the client aswell.
