### ISSUE TITLE
Didn't receive my items

### ISSUE THREAD

**Issue by jochuan** [henkelmax/gravestone#27]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I falled in lava in the nether while i was on a server with a friend and i after a while digging through the lava to get in my gravestone i broke it and it was empty

**Steps to reproduce the issue**
My computer was running the server and it was with low memory so i was lagging a little in the game
**Expected behavior**
It should give the items to my inventory
**Log files**
https://gist.github.com/jochuan/0d67a42ac21447dfe5b0517abbb19960
https://gist.github.com/jochuan/d803611423770609e9c0264efe4ddf74
**Versions**
- 1.16.4
- 35.1.13
- 1.0.5

**Other mods**
Ambient sounds, Ars Nouveau, Biomes O Plenty, Botania, Ice and Fire, JEI, Optifine, Random Patches, Mouse Tweaks, Serene Seasons, Sound Filters, Spiders 2.0, Xaeros Minimap, Enhanced Visuals 

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I can't se any errors in your logs. Are you sure your items didn't fall into the lava? What are your config settings? Please send me the contents of your `gravestone-server.toml` config file.

**Comment by jochuan** [comment]
#If this is set to true you get an obituary after you died
enable_obituary = true
#The blocks that can be replaced with a grave
#If it starts with '#' it is a tag
replaceable_blocks = ["#gravestone:grave_replaceable"]
#If this is set to true the obituary will be taken out of your inventory when you break the grave
remove_obituary = false
#If this is set to true only the player that owns the grave and admins can break the grave
only_owners_can_break = false
#If this is set to true the ghost of the dead player will be spawned when the grave is broken
spawn_ghost = false
#If this is set to true the ghost player will defend the player
friendly_ghost = true
#If this is set to true you get your items back into your inventory by sneaking on the grave
sneak_pickup = false
#If this is set to true you get your items sorted back into your inventory by breaking the grave
break_pickup = true

**Comment by jochuan** [comment]
> I can't se any errors in your logs. Are you sure your items didn't fall into the lava? What are your config settings? Please send me the contents of your `gravestone-server.toml` config file.

If by dying inside the lava the items don't go to the gravestone and are destroyed then yes, but i died on lava a few times before and the items were there when i broke the gravestone

**Comment by henkelmax** [comment]
According to your config, your items should get straight into your inventory when broken.
You can restore your lost items if you have your obituary:

![image](https://user-images.githubusercontent.com/13237524/103148084-4aa7b400-475c-11eb-87fc-a48475436092.png)

**Comment by jochuan** [comment]
So i always throw my obituary away since i use a mini map that shows me the last place that i died is there another way to get my death id ?

**Comment by henkelmax** [comment]
That's not good.
You can find out the death id by searching your `deaths` folder in your world folder.

**Comment by jochuan** [comment]
![image](https://user-images.githubusercontent.com/11268912/103158797-da6f5180-47a0-11eb-9e72-2eecee7b6b0b.png)

**Comment by henkelmax** [comment]
Yes, just sort by newest and use that ID.

**Comment by jochuan** [comment]
So there is two folders that i think that are from my friend and from me, but how i can get the death id from those ? when i open one of those dat files with the windows notepad i can see some text with meaning but the rest is like this
![image](https://user-images.githubusercontent.com/11268912/103158856-70a37780-47a1-11eb-9849-7749ec40c533.png)

**Comment by henkelmax** [comment]
The death id is the file name.

**Comment by jochuan** [comment]
It worked thanks, should i close this issue ?

**Comment by henkelmax** [comment]
Yes, but please let me know if this issue occurs again.
