### ISSUE TITLE
Death message on a grave shows twice everytime

### ISSUE THREAD

**Issue by InuYasha86000** [henkelmax/gravestone#28]
for 1.12.2 Version 1.3.1 with extention 1.3.5.1, anytime any player right clicks a grave to see the death message, it always shows it twice in a row, for example:
*right click grave*
Bob died by skeleton, lived 10 days
Bob died by skeleton, lived 10 days

This happens with every player, at first I thought it was only ops but even new players have this happening, and I couldn't find a setting that could be doing this without turning the messages completely off.

**Comment by henkelmax** [comment]
There is no version `1.3.1` for Minecraft `1.12.2`.

There is no message `Bob died by skeleton, lived 10 days`.

I'm pretty sure this isn't the right mod.

**Comment by InuYasha86000** [comment]
I appologise as I got this mod confused with another, I am really sorry.
