### ISSUE TITLE
Noob issue ?

### ISSUE THREAD

**Issue by sdkyron** [henkelmax/gravestone#30]
Hi,

Ok this is gonna sound ridiculous i know but i'm fairly new to server hosting in minecraft, every single of my plugins work fine exept this one.
I'm running paper spigot on my server, moved the gravestone-1.16.4-1.0.8 in my plugins folder, as usual, but it doesn't work in game, no gravestone, nothing.

**Comment by henkelmax** [comment]
This isn't a plugin. It's a Forge mod.

**Comment by sdkyron** [comment]
Does that mean that i can't use your mod since my server is running
paperspigot ?

**Comment by henkelmax** [comment]
Yes, You would need a Forge server and also a client with Forge. The mod has to be installed on both sides. That's the difference between a Forge mod and a Bukkit/Spigot plugin.
