### ISSUE TITLE
Gravestone has no items from previous gravestone when killed trying to break gravestone

### ISSUE THREAD

**Issue by ferjif** [henkelmax/gravestone#31]
**Bug description**
I encountered a very edge case in which I died and then I respawned at my home then I used /back from a mod I forgot the name to. it teleported me on top of my gravestone. As I broke my gravestone a skeleton shot me and I died. then when i used /back again and broke my tombstone and none of my stuff was in the gravestone.

**Steps to reproduce the issue**
1. have some stuff on you and die.
2. die
3. comeback
4. have a mob like a skeleton try to kill you
5. break the tombstone at the moment you are about to die.
**Expected behavior**
It should have the stuff in it of course.

**Versions**
- Minecraft 1.16.4
- Forge 35.1.14
- Mod 1.0.7

**Other mods**
I don't know the name of the mod but it was in the ftb presents dierwolf20 1.16 modpack.

**Comment by henkelmax** [comment]
Please fill out the complete template. You are missing log files.
Were you able to reproduce it?
