### ISSUE TITLE
Gravestone Disappeared

### ISSUE THREAD

**Issue by Cryoraven** [henkelmax/gravestone#32]
Died to a Dragon from ice and fire and died in the water. Gravestone is gone and nowhere to be found. I have my obituary that says the coordinates and no gravestone. Is there something that happens when you die in water?

**Comment by Cryoraven** [comment]
What probably happened is the dragon destroyed my grave and my stuff despawned

**Comment by henkelmax** [comment]
Next time when reporting an issue, please use the provided templates.

**Comment by henkelmax** [comment]
You may also report this to the ice and fire devs, as the mod should not destroy this block.
