### ISSUE TITLE
Mod Causes Server Not to Load

### ISSUE THREAD

**Issue by aelizardbeacon165** [henkelmax/gravestone#33]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
Started a new server using forge on ScalaCube. Server started fine. I downloaded the mod files I wanted and added them to the mods folder in the console. After rebooting the server and rejoining an error came up "Non [a-z0-9_.-] character in namespace of location: #gravestone:grave_replaceable." I am using the latest update for both Forge (forge-1.16.5-36.0.1) and the mod (gravestone-1.16.5-1.0.0)

**Steps to reproduce the issue**
1. Go to 'File Manager'
2. Click on 'mods'
3. Upload gravestone-1.16.5-1.0.0
4. Reboot server
5. Open Minecraft launcher
6. Launch multiplayer world with mods
7. Get error prompt

**Expected behavior**
Expected the world to load

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 36.0.1
- Mod version 1.16.5-1.0.0

**Other mods**
EasierSleeping-1.16.5-1.0.0
forgemod_VoxelMap-1.10.14_for_1.16.4

**Screenshots (Optional)**
![minecraft server error gravestones](https://user-images.githubusercontent.com/77903961/105617416-20253700-5dac-11eb-8d05-509e110b23ba.png)

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Please provide your log files.

**Comment by aelizardbeacon165** [comment]
START TIME: Sun Jan 24 23:34:20 MSK 2021
[32m[20:34:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.0.1, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[m[32m[20:34:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_191 by Oracle Corporation
[m[32m[20:34:22] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[20:34:22] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/minecraft/server/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[m[32m[20:34:23] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[m[32m[20:34:32] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.0.1, for MC 1.16.5 with MCP 20210115.111550
[m[32m[20:34:32] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.0.1 Initialized
[m[1;31m[20:34:33] [main/ERROR] [minecraft/Util]: No data fixer registered for gravestone:player_ghost
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file /home/minecraft/server/config/easier_sleeping.toml is not correct. Correcting
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key sleep_percent was corrected from null to 50
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key sleep_message was corrected from null to is now in bed.
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key wake_message was corrected from null to stood up.
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key morning_message was corrected from null to Good Morning
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key dimensions was corrected from null to [minecraft:overworld]
[m[33m[20:34:33] [main/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key dimension_list_type was corrected from null to SLEEP_ACTIVE
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: Loading "Easier Sleeping" Config
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_percent] = 50
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_message] = is now in bed.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [wake_message] = stood up.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [morning_message] = Good Morning
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimensions] = [minecraft:overworld]
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimension_list_type] = SLEEP_ACTIVE
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: "Easier Sleeping" Config loaded
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: Loading "Easier Sleeping" Config
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [sleep_percent] = 50
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [sleep_message] = is now in bed.
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [wake_message] = stood up.
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [morning_message] = Good Morning
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [dimensions] = [minecraft:overworld]
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: Loading "Easier Sleeping" Config
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: [dimension_list_type] = SLEEP_ACTIVE
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_percent] = 50
[m[32m[20:34:33] [main/INFO] [de.ge.ea.co.MainConfig/]: "Easier Sleeping" Config loaded
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_message] = is now in bed.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [wake_message] = stood up.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [morning_message] = Good Morning
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimensions] = [minecraft:overworld]
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimension_list_type] = SLEEP_ACTIVE
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: "Easier Sleeping" Config loaded
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: Loading "Easier Sleeping" Config
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_percent] = 50
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [sleep_message] = is now in bed.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [wake_message] = stood up.
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [morning_message] = Good Morning
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimensions] = [minecraft:overworld]
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: [dimension_list_type] = SLEEP_ACTIVE
[m[32m[20:34:33] [Thread-1/INFO] [de.ge.ea.co.MainConfig/]: "Easier Sleeping" Config loaded
[m[32m[20:34:33] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[m[32m[20:34:33] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA Current: 36.0.1 Target: 36.0.1
[m[32m[20:34:33] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [gravestone] Starting version check at https://maxhenkel.de/update/gravestone.json
[m[32m[20:34:34] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [gravestone] Found status: UP_TO_DATE Current: 1.16.5-1.0.0 Target: null
[m[32m[20:34:38] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[m[33m[20:34:39] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[20:34:39] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[20:34:39] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[20:34:39] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[20:34:39] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[32m[20:34:39] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.5-36.0.1-universal.jar, forgemod_VoxelMap-1.10.14_for_1.16.4.jar, EasierSleeping-1.16.5-1.0.0.jar, gravestone-1.16.5-1.0.0.jar
[m[32m[20:34:40] [Worker-Main-2/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[m[32m[20:34:41] [Worker-Main-2/INFO] [minecraft/AdvancementList]: Loaded 927 advancements
[m[32m[20:34:44] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.5
[m[32m[20:34:44] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[m[32m[20:34:44] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[m[32m[20:34:44] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
[m[?1h=[?2004h> 
[K[32m[20:34:44] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:2249
[m> 
[K[32m[20:34:44] [Server thread/INFO] [minecraft/NetworkSystem]: Using epoll channel type
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file ./world/serverconfig/gravestone-server.toml is not correct. Correcting
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key enable_obituary was corrected from null to true
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key replaceable_blocks was corrected from null to [#gravestone:grave_replaceable]
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key remove_obituary was corrected from null to false
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key only_owners_can_break was corrected from null to false
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key spawn_ghost was corrected from null to false
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key friendly_ghost was corrected from null to true
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key sneak_pickup was corrected from null to false
[m> 
[K[33m[20:34:45] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key break_pickup was corrected from null to true
[m> 
[K[32m[20:34:45] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
[m> 
[K[32m[20:34:45] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[m> 
[K[32m[20:34:46] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:46] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:47] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:47] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m> 
[K[32m[20:34:51] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 28%
[m> 
[K[32m[20:34:51] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 50%
[m> 
[K[32m[20:34:52] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 50%
[m> 
[K[32m[20:34:52] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 50%
[m> 
[K[32m[20:34:53] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 50%
[m> 
[K[32m[20:34:53] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 51%
[m> 
[K[32m[20:34:54] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 51%
[m> 
[K[32m[20:34:54] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 52%
[m> 
[K[32m[20:34:55] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 53%
[m> 
[K[32m[20:34:55] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 54%
[m> 
[K[32m[20:34:56] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 57%
[m> 
[K[32m[20:34:56] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 58%
[m> 
[K[32m[20:34:57] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 59%
[m> 
[K[32m[20:34:57] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 60%
[m> 
[K[32m[20:34:58] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 60%
[m> 
[K[32m[20:34:58] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 62%
[m> 
[K[32m[20:34:59] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 65%
[m> 
[K[32m[20:34:59] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 67%
[m> 
[K[32m[20:35:00] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 68%
[m> 
[K[32m[20:35:00] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 69%
[m> 
[K[32m[20:35:01] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 71%
[m> 
[K[32m[20:35:01] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 71%
[m> 
[K[32m[20:35:02] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 72%
[m> 
[K[32m[20:35:02] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 73%
[m> 
[K[32m[20:35:03] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 75%
[m> 
[K[32m[20:35:03] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 77%
[m> 
[K[32m[20:35:04] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 78%
[m> 
[K[32m[20:35:04] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 80%
[m> 
[K[32m[20:35:05] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 82%
[m> 
[K[32m[20:35:05] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
[m> 
[K[32m[20:35:06] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 84%
[m> 
[K[32m[20:35:06] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 86%
[m> 
[K[32m[20:35:07] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 87%
[m> 
[K[32m[20:35:07] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 90%
[m> 
[K[32m[20:35:08] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 92%
[m> 
[K[32m[20:35:08] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 94%
[m> 
[K[32m[20:35:09] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 96%
[m> 
[K[32m[20:35:09] [Worker-Main-3/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 98%
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 24135 ms
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/DedicatedServer]: Done (25.014s)! For help, type "help"
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/DedicatedServer]: Starting GS4 status listener
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/RConThread]: Thread Query Listener started
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/DedicatedServer]: Starting remote control listener
[m> 
[K[32m[20:35:10] [Query Listener #1/INFO] [minecraft/QueryThread]: Query running on 0.0.0.0:25565
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/RConThread]: Thread RCON Listener started
[m> 
[K[32m[20:35:10] [Server thread/INFO] [minecraft/MainThread]: RCON running on 0.0.0.0:2248
[m> whitelist on
[?1l>[?1000l[?2004l[?1h=[?2004h> 
[K[32m[20:39:47] [Server thread/INFO] [minecraft/DedicatedServer]: Whitelist is now turned on
[m> whitelist add AElizrdbeacon165
[?1l>[?1000l[?2004l[?1h=[?2004h> 
[K[32m[20:40:07] [Server thread/INFO] [minecraft/DedicatedServer]: Added AElizrdbeacon165 to the whitelist
[m> whitelist add curious_Corvid
[?1l>[?1000l[?2004l[?1h=[?2004h> 
[K[32m[20:41:36] [Server thread/INFO] [minecraft/DedicatedServer]: Added curious_Corvid to the whitelist
[m> whitelist add Navaelandi
[?1l>[?1000l[?2004l[?1h=[?2004h> 
[K[32m[20:42:07] [Server thread/INFO] [minecraft/DedicatedServer]: Added Navaelandi to the whitelist
[m> 
[K[32m[20:46:24] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player AElizrdbeacon165 is 587a4fdb-8669-4fc7-9486-859d3bd57c34
[m> 
[K[32m[20:46:26] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@589054f0[id=587a4fdb-8669-4fc7-9486-859d3bd57c34,name=AElizrdbeacon165,properties={textures=[com.mojang.authlib.properties.Property@48da672a]},legacy=false] (/24.127.147.74:53733) lost connection: Disconnected
[m>

**Comment by aelizardbeacon165** [comment]
[9e9043cced3d2daa25164e252d93851d-97ad20cf7147642053b18ce6adfac3687a8fca47.zip](https://github.com/henkelmax/gravestone/files/5863164/9e9043cced3d2daa25164e252d93851d-97ad20cf7147642053b18ce6adfac3687a8fca47.zip)

**Comment by henkelmax** [comment]
Please also include your config

**Comment by aelizardbeacon165** [comment]
[server config.zip](https://github.com/henkelmax/gravestone/files/5863293/server.config.zip)

**Comment by aelizardbeacon165** [comment]
The server isn't showing that a config file exists for gravestone unless it's under a different name

**Comment by henkelmax** [comment]
I can't find anything wrong. Please try a fresh install of your minecraft instance.

**Comment by aelizardbeacon165** [comment]
I tried a fresh install with Forge 36.0.0 instead of 36.0.1 and it seemed to work fine now.
