### ISSUE TITLE
Conflict with Travelers Backpack

### ISSUE THREAD

**Issue by ooainaut** [henkelmax/gravestone#34]
Travelers backpack somehow takes over gravestone if they are loaded at the same time. Gravestone wont spawn graves and wont put the config in the world/serverconfig even after travelers is removed 
although, strangely it will recreate the travelers config in .minecraft/config after removing travelers mod and travelers config instead of gravestone config . But if they (the mods) are both removed and then gravestone is loaded into a world first and then travelers, it all works fine so far.
[debug.log](https://github.com/henkelmax/gravestone/files/5861654/debug.log)
[latest.log](https://github.com/henkelmax/gravestone/files/5861657/latest.log)

**Comment by henkelmax** [comment]
Please fill out the complete bug template.

**Comment by henkelmax** [comment]
So, I tested it, and it works perfectly fine. If you die with the backpack on, it just spawns next to the gravestone.

![2021-01-24_10 38 16](https://user-images.githubusercontent.com/13237524/105626556-b1d68800-5e30-11eb-9aaa-446807f026a0.png)

Please try a clean install of your minecraft instance and report this issue again (Please fill out the bug template next time) if it still doesn't work.
