### ISSUE TITLE
Gravestone makes my forge not load, but i dont see any files of it anywhere

### ISSUE THREAD

**Issue by PyroTheReaper** [henkelmax/gravestone#36]
**Steps to reproduce the issue**
1. Launch Minecraft from forge 1.7.2
2. Bar goes up and stops, then closes the launcher
3. Open crash logs

**Expected behavior**
It just doesnt boot up. Im not familiar with mods, and my friend tried to get me into modded a while back and i do remember the pack had gravestone, but i deleted all the files for the mods in the modpack in both the mods folder and the config folder, so sorry if anything isnt clear or seems stupid.

**Log files**
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- MOD gravestone --
Details:
	Mod File: gravestone-1.10.3.jar
	Failure message: Mod gravestone requires minecraft 1.13.2
		Currently, minecraft is 1.16.4
	Mod Version: 1.12.7
	Mod Issue URL: https://minecraft.curseforge.com/projects/gravestone-mod/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Versions**
- 1.7.2
- 1.7.2
- 1.12.7
**Other mods**
Optifine 1.7.2
NEU

**Comment by henkelmax** [comment]
I have no clue what you are doing.
Please tell me your exact minecraft version, forge version and mod version. Also pleas provide your log files.

**Comment by henkelmax** [comment]
Closed due to inactivity.
