### ISSUE TITLE
[Feature Request] Curios support for slot restoration

### ISSUE THREAD

**Issue by FreneticScribbler** [henkelmax/gravestone#37]
**Is your feature request related to a problem? Please describe.**
The new slot restoration feature is super awesome UX. I have a lot of [curios](https://www.curseforge.com/minecraft/mc-mods/curios) though, and the mod doesn't seem to be able to cope with putting these back into their slots. 

**Describe the solution you'd like**
If you could look at adding explicit support for the Curios API, that'd be super sweet! Even better if you could manage to write a system that copes with any extra inventory slots but I understand that may be tricky/impossible...in any case Curios API is the big one cause it has so many slots...

**Comment by FreneticScribbler** [comment]
I...did not intentionally add the label nor do that assignment...is that part of the template? Is it meant to be?

**Comment by henkelmax** [comment]
I'm sorry, but I don't intend to add compatibility with slots from other mods. This would add too many dependencies to the mod that would slow down the mods release when updating to a new minecraft version.

**Comment by GamingInfinite** [comment]
I mean it could be implemented as an API hook sort of thing.  I've seen other mods do it where if this specific mod is here, add this functionality.  For instance, if someone wants to add support for their mod, they just call a method from this mod to add what's needed.

**Comment by JustJinxed** [comment]
Oh well, guess I'll use Enigmatic then- if you ever reconsider, curios-api is pretty much a staple. You're talking a good 20 mods that add this extra gear.

**Comment by e913a** [comment]
> This would add too many dependencies to the mod that would slow down the mods release when updating to a new minecraft version.

I understand the reason and as a maintainer for other projects, I would do the same.

It seems that [Curios API (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/curios) has been discontinued as of 1.21.

Most major mods that still target `1.20.1`.
I'm interested into developing a mod that add compatibility for this project with Curios API.

Curios API project is already documented, I'm aware this is out of scope for this project but can you give me some hint on how to change how to change `Transfer Items` behavior? So I can get access to the equipped items of Curios inventory and return them back to where they were before the player die in game. So it will be automatically sorted.

I will search for the function that get the Curios inventory instance from their docs though I would like an example on how can I add this feature from [Corpse](https://modrinth.com/mod/corpse) mod side.
