### ISSUE TITLE
[1.16.1] Сonfiguration of dimension names always by default

### ISSUE THREAD

**Issue by gekkone** [henkelmax/gravestone#4]
**Bug description**
Can't change the dimension name, because the value of the dimension_names key is always considered invalid and the default value is used

**Log files**
Configuration file /home/gekkone/.minecraft/config/gravestone-client.toml is not correct. Correcting
 [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key dimension_names was corrected from [minecraft:overworld=Overworld, minecraft:nether=Nether, minecraft:the_end=The End] to [minecraft:overworld=Overworld, minecraft:nether=Nether, minecraft:the_end=The End]

**Versions**
- 1.16.1
- 32.0.108
- 1.0.6

**Comment by henkelmax** [comment]
This was fixed with #2 
Consider updating to 1.16.2

**Comment by gekkone** [comment]
The forge API doesn't allow you to migrate this fix to 1.16.1?

**Comment by henkelmax** [comment]
No. I don't have time to maintain every minecraft version. I usually support the latest two or three major versions.
And like forge I am not focusing on minor versions.
