### ISSUE TITLE
Tombstones getting in the way of minigame builds.

### ISSUE THREAD

**Issue by Blackwolf291** [henkelmax/gravestone#42]
**Is your feature request related to a problem? Please describe.**
Hi, I run a group server, and we're running into a situation where because we're starting to build sometimes lethal minigames, wwe've reached the conclusion that the tombstone preserving your dropped loot is becoming a hindrance, because it spawns undesirable platforms in the middle of redstone contraptions, platforming challenges, and player kill traps, even when the player has no gear on them.

**Describe the solution you'd like**
Would it be possible to add a configuration, where the players still recieve the obituary, stating where they died and all that information, but no tombstone is created? The obituary is extremely useful for finding your death site, but on our late game server, we find the tombstone spawn becoming a problem.

**Describe alternatives you've considered**
Our main alternative would be to disable the mod altogether. Being able to exclude map regions or disable tombstones for specific players on the fly would also resolve the issue, with the upside of leaving the mod's benefits in tact.

**Comment by henkelmax** [comment]
For this case I would recommend the corpse mod: https://www.curseforge.com/minecraft/mc-mods/corpse
You could just kill the corpses in the area of your minigames with a command block. Alternative you can set the corpse to despawn after a set amount of time.
