### ISSUE TITLE
Per player graves OR only get a gravee if you have a certain item

### ISSUE THREAD

**Issue by ShadwDrgn** [henkelmax/gravestone#46]
Would be VERY cool if we could have a craftable item that makes it so that a grave drops when we die. The item would be removed OR a charge would be used up (limited charges? could be recharged with right click at cost of hunger?)

Alternatively it'd be nice if we could set only certain players to get a grave when they die. This could be via opt in with a command or maybe admin only command to set it on a player.

**Comment by cybertron2600** [comment]
I'd agree, a method in which you can earn a gravestone sounds like a good middle ground. Otherwise it's just free and you don't value it.

**Comment by henkelmax** [comment]
> Would be VERY cool if we could have a craftable item that makes it so that a grave drops when we die.

What do you mean with that?

**Comment by ShadwDrgn** [comment]
For example I might have to craft an item from gold and w/e else that is some kind of "charm." If you die and that item is on you it leaves behind a grave and the item is destroyed. Alternatively other fun "balance" mechanics could be implemented like right clicking the item to add ender pearls or some other fuel type item to "charge" it and dying with it on you could reduce the charge so that you only get a grave if there is enough charge in the item. This item could be enabled or disabled via config so people who just want free graves can just not turn it on (or turn it off if it's on by default).

**Comment by henkelmax** [comment]
I don't know if this fits into the style of this mod. What would that item be?

**Comment by ShadwDrgn** [comment]
> I don't know if this fits into the style of this mod. What would that item be?

It would be anything you want it to be. Maybe like a weird charm or voodoo doll type thing or a little magic coffin or a like a "last will" scroll that says "bury me with my belongings" on it when you read it.

**Comment by henkelmax** [comment]
Nah, sorry, this really doesn't fit into the style of this mod.
I made this mod so you never lose your items. And having no grave spawn when you don't have a certain item is frustrating for players.

**Comment by ShadwDrgn** [comment]
You could make this a config option to avoid frustration for players who want an easier mode. The point here is that some players do NOT want forced graves but want the option for graves. Also worth noting that this would be something no one has done yet and you'd be the first, but i will leave it at that since you closed the issue. Thanks for looking at it :)

**Comment by henkelmax** [comment]
Maybe I will add that as an optional feature, but I have a lot to do right now. So don't expect it in the near future.
