### ISSUE TITLE
Disable obituary option missing from config file

### ISSUE THREAD

**Issue by spyjdh** [henkelmax/gravestone#51]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/gravestone/faq)!**

The Obituary
Everytime you die you get an obituary. If you don't want that you can disable it in the config.

This is the generated config file;
#If this is set to true the players head will be rendered on the gravestone when there is a full block under it
render_skull = true
#The color of the text at the gravestone (Hex RGB)
grave_text_color = "FFFFFF"

How do I disable the obituary?

**Comment by henkelmax** [comment]
Read the FAQ

**Comment by spyjdh** [comment]
I read the FAQ at your site:
https://modrepo.de/minecraft/gravestone/faq

I still dont see what change I need to make to the config file.
