### ISSUE TITLE
1.16.5 How disable message in chat?

### ISSUE THREAD

**Issue by Senyum** [henkelmax/gravestone#54]
Hi, is it possible to somehow disable the chat message if the player dies with nothing in their inventory?
![Screenshot_4](https://user-images.githubusercontent.com/36424845/114987675-19cfc400-9e9e-11eb-9c6c-7e50b279bf2a.png)

**Comment by henkelmax** [comment]
This message does not even exist in this mod:

https://github.com/henkelmax/gravestone/blob/master/src/main/resources/assets/gravestone/lang/en_us.json
