### ISSUE TITLE
Gravestones dropping items

### ISSUE THREAD

**Issue by J4mes2020** [henkelmax/gravestone#59]
Hello, so i used the gravestone mod in my mohist server, with some other plugins and mods. And when a player dies it creates a gravestone but drops all the items on the floor anyway, it gives them a Obituary, but just doesn't keep the items in the grave

MOD list:
![image](https://user-images.githubusercontent.com/65375012/116822408-88876f80-ab76-11eb-87b1-5883e93bdcc5.png)
![image](https://user-images.githubusercontent.com/65375012/116822414-91784100-ab76-11eb-9ddd-e4d51493cead.png)

plugins:
![image](https://user-images.githubusercontent.com/65375012/116822426-9fc65d00-ab76-11eb-859f-848ca177201f.png)

**Comment by henkelmax** [comment]
I'm sorry, but this mod does not support running with plugins.
