### ISSUE TITLE
Bug for gravestone 1.16.2-1.0.4

### ISSUE THREAD

**Issue by Masaki123456** [henkelmax/gravestone#6]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
Using gravestone-1.16.2-1.0.4 on Forge 1.16.2-33.0.61 for a modded server and game wont open. Tried with only gravestone mod and got same issue. Game would go through mod loading and would crash. Issue also occurs when loading gravestone versions 1.16.2-1.0.5 and 1.0.6. Error that comes up is: 
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Rendering overlay
Exit Code: -1
TL;DR: Game wont load when mod is installed

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

1. Go to http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.16.2.html
2. Click on installer and wait for download
3. Click on Install Client and then Ok
4. Wait for installation to complete
5. Go to https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/files/3040798
6. Click on purple download button and wait for download to finish
7. Drag downloaded file into minecraft mods folder.
8. Open Minecraft Launcher and make sure selected version is forge 1.16.2-forge-33.0.61
9. Click Play and wait for crash
10. See error

**Expected behavior**
I expected to be able to open the game and play with the mod

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
https://gist.github.com/Masaki123456/94116984f2b0395675e09eaad25dcb66#file-crash-2020-09-15_11-58-17-client-txt
**Versions**
- Minecraft version 1.16.2
- Forge version 1.16.2-33.0.61
- Mod version 1.16.2-1.0.4

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
Problem occurs w/ and w/o other mods installed.
List of mods used:
ftb-chunks-1.1.1.32
ftb-gui-library-library-1.0.0.18
jei-1.16.2-7.3.2.25
mana-and-artifice-1.0.7.1
curios-forge-1.16.2-4.0.0.1
mana-plus-1.0.2

**Screenshots (Optional)**
Screenshots of the issue.
![Crashgravestone](https://user-images.githubusercontent.com/71347298/93253478-c51f6b80-f74b-11ea-9689-5f4b32179951.PNG)

**Comment by henkelmax** [comment]
Unfortunately I am not able to reproduce this issue.
Can you make sure that this is no general problem with your Minecraft installation?
It seems that the problem is related to the Forge config system.
My guess would be that it somehow is not able to read or write the config file in your filesystem.

Please try the following things:

- Try reinstalling Minecraft
- Try installing your Minecraft instance to a different location than `.minecraft`
- Try running any other mod except this mod (that creates a config file)

**Comment by Masaki123456** [comment]
Thank you for the quick response! I fixed the issue by deleting the config file. Thank you for your time!

**Comment by henkelmax** [comment]
No problem.
