### ISSUE TITLE
NBT larger than 2MB disconnects player from server

### ISSUE THREAD

**Issue by lcy0x1** [henkelmax/gravestone#60]
I was playing Mineshafts and Monsters in a server. I get this error after getting killed and kicked out of the server, and can never login. After the server moderator deleted my player data file, I was able to join again, but whenever I approach the chuck that contains my gravestone, I get this error again.

<img width="1741" alt="Screen Shot 2021-05-22 at 8 56 48 PM" src="https://user-images.githubusercontent.com/31638432/119227479-a70ed400-bb40-11eb-9508-79a0594cd286.png">

**Comment by henkelmax** [comment]
Please fill out the complete bug template.
