### ISSUE TITLE
Possible to change default server config?

### ISSUE THREAD

**Issue by Banaando** [henkelmax/gravestone#61]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/gravestone/faq)!**
By default, players can't sneak on their graves to pick up their items. I know I can change this to make it so they can, but I can only do it on a per server/world basis. Is it possible to make it so this option will be enabled by default on all worlds?

**Comment by henkelmax** [comment]
Just put it into the `defaultconfigs` folder.
