### ISSUE TITLE
[1.12.2] Baubles compatibility

### ISSUE THREAD

**Issue by marshallgwentz** [henkelmax/gravestone#63]
Do any of the releases of this mod for 1.12.2 have any problems with the Baubles mod? I'm running it as part of a private modpack I'm currently testing, and I wanted to add this mod to the pack.

**Comment by henkelmax** [comment]
There shouldn't be any problems with it.

**Comment by JustJinxed** [comment]
Seems the 1.18.2 version doesn't re-equip bauble items?
https://youtu.be/SJBgj3qkUqs?t=1941

Could you maybe consider this addition?
