### ISSUE TITLE
Inventory held with Carry On mod (by Tschipp) is not saved upon death and vanishes.

### ISSUE THREAD

**Issue by Galicjanin** [henkelmax/gravestone#64]
Inventory held with Carry On mod (by Tschipp) is not saved upon death and vanishes.

Steps to reproduce:
Install Gravestone and Carry On mods.
Pick up block with blockdata (like chest)
Kill yourself
Restore items from grave and notice lack of carried block.

Note: Carry On can also hold mobs in hands.

**Comment by henkelmax** [comment]
Please fill out the bug template.

**Comment by henkelmax** [comment]
Closed due to inactivity
