### ISSUE TITLE
Crash on right-clicking gravestone.

### ISSUE THREAD

**Issue by Angular-Angel** [henkelmax/gravestone#67]
**Bug description**
Crash on right clikcing gravestone

**Steps to reproduce the issue**
1. Die with stuff in your inventory
2. Right click on your gravestone.
3. Profit. (Crash)

**Expected behavior**
Right clicking should show text without crashing.

**Log files**

[crash-2021-08-06_19.33.15-server.txt](https://github.com/henkelmax/gravestone/files/6948429/crash-2021-08-06_19.33.15-server.txt)

**Versions**
- Minecraft version: 1.17.1
- Forge version: 37.0.27
- Mod version: 1.0.3

**Comment by henkelmax** [comment]
You are using https://www.curseforge.com/minecraft/mc-mods/wthit which implements the WAILA API. But this mod uses https://www.curseforge.com/minecraft/mc-mods/jade
It seems that wthit fails to ckeck if the WAILA integration is compatible.
I would suggest reporting it to whit.
