### ISSUE TITLE
Crash with Epic Fight Mod

### ISSUE THREAD

**Issue by sclozes** [henkelmax/gravestone#68]
**Bug description**
When I'm trying to open the obituary the game crashes.

**Expected behavior**
I expected to open the obituary and see the place I died.

**Log files**
https://gist.github.com/sclozes/c69c641b26fbada383cb755482d6e5ff

**Versions**
- Minecraft version: 1.16.5
- Forge version: 1.16.5-forge-36.2.2
- Mod version: gravestone-1.16.5-1.0.6

**Other mods**
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod
https://www.curseforge.com/minecraft/mc-mods/create
https://www.curseforge.com/minecraft/mc-mods/flywheel
https://www.curseforge.com/minecraft/mc-mods/simple-planes
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod
https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry
https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
https://www.curseforge.com/minecraft/mc-mods/citadel/
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
https://www.curseforge.com/minecraft/mc-mods/dungeons-mod
https://www.curseforge.com/minecraft/mc-mods/security-craft
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
https://www.curseforge.com/minecraft/mc-mods/iron-chests
https://www.curseforge.com/minecraft/mc-mods/small-ships
https://www.curseforge.com/minecraft/mc-mods/storage-drawers
https://www.curseforge.com/minecraft/mc-mods/macaws-bridges
https://www.curseforge.com/minecraft/mc-mods/obfuscate/
https://www.curseforge.com/minecraft/mc-mods/jei
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod
https://www.curseforge.com/minecraft/mc-mods/aquaculture
https://www.curseforge.com/minecraft/mc-mods/tetra
https://www.curseforge.com/minecraft/mc-mods/mgui
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-more-furniture-mod
https://www.curseforge.com/minecraft/mc-mods/tree-felling-made-lightweight-and-with-mod
https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings
https://www.curseforge.com/minecraft/mc-mods/abnormals-core

https://www.curseforge.com/minecraft/mc-mods/death-finder
^^^ I use this mod because the obituary does not work

**Screenshots (Optional)**
https://www.mediafire.com/file/ikgrxvw0lk21nyx/Base_Profile_2021.08.13_-_04.54.04.01.mp4/file

**Comment by henkelmax** [comment]
I can see no crash in your logs.

Please test if this also occurs without any other mods installed.

**Comment by henkelmax** [comment]
Seems to be related to https://github.com/henkelmax/corpse/issues/52

Can you please report this issue to the epic fight mod issue tracker as well?

**Comment by sclozes** [comment]
Yes, it is related to [henkelmax/corpse#52](https://github.com/henkelmax/corpse/issues/52), the game freezes and crashes. and also I tried to use the Corpse Mod instead of the Gravestone mod and the same problem occurred.
I'm going to make a report to the epic fight mod issue tracker.

Here is a screenshot of the error from the Minecraft Launcher:
![Captdfdfure](https://user-images.githubusercontent.com/59666888/129374418-8e23f091-ffa6-4519-a25f-0903c8c65f15.PNG)

**Comment by henkelmax** [comment]
No crash report?

**Comment by sclozes** [comment]
I can't find a crash report, the game just freeze and crash after a couple of minutes

**Comment by henkelmax** [comment]
There seem to be multiple reports like this on their issue tracker:

https://github.com/Yesssssman/epicfightmod/issues/452
https://github.com/Yesssssman/epicfightmod/issues/394

Some of them even without Corpse/Gravestone.
Can you please test if the crash occurs without the Corpse mod?

**Comment by sclozes** [comment]
It does occur without the Corpse mod. (I replaced the Gravestone mod with the Corpse mod, I didn't use them at the same time)

**Comment by sclozes** [comment]
I don't really know how these things work but maybe the Epic Fight Mod changes the death system which makes the Gravestone mod and or the Corpse mod not function correctly.

**Comment by henkelmax** [comment]
> It does occur without the Corpse mod. (I replaced the Gravestone mod with the Corpse mod, I didn't use them at the same time)

No I mean if it happens without any of those two mods (Corpse/Gravestone).

**Comment by sclozes** [comment]
How can it happen without those mods?
It happens when I open the obituary on the Gravestone mod and on the Corpse mods it happens when I open the death history.

**Comment by henkelmax** [comment]
> How can it happen without those mods?
> It happens when I open the obituary on the Gravestone mod and on the Corpse mods it happens when I open the death history.

Oh sorry I forgot :D

**Comment by sclozes** [comment]
Any updates?

**Comment by aaronhowser1** [comment]
I don't crash when I die with EFM. Tested in and out of battle mode, with the EFM config set to disable custom animations outside of battle mode.
