### ISSUE TITLE
Minor: Wearable backpack compatibility

### ISSUE THREAD

**Issue by BjornTjockPals** [henkelmax/gravestone#69]
Hi! Could you add compatibility fix for copygirl's WearableBackpacks?

Right now, after death backpack from that mod spawns on your death place, and your grave spawns on top of it. Its a minor thing but looks quirky. 
Possible solution could be to spawn gravestone one block next to your death location if WearableBackpacks are installed.

![image](https://user-images.githubusercontent.com/88323403/130647483-7490ad98-5bbf-47be-8dad-5acdb3198dc4.png)

Also if `Drop as Block on Death` is set to `false` (in Wearable backpack's settings) your backpack with its content drops on the ground instead being saved in the grave.

**Comment by henkelmax** [comment]
> Also if Drop as Block on Death is set to false (in Wearable backpack's settings) your backpack with its content drops on the ground instead being saved in the grave.

This is an issue by Wearable Backpacks.

Version 1.12.2 of the gravestone mod is also not supported anymore.
