### ISSUE TITLE
did not work

### ISSUE THREAD

**Issue by Parciwal** [henkelmax/gravestone#70]
**Bug description**
It just Did not work. This is the only time so far

**Steps to reproduce the issue**
1. build a wall
2. fall down the edge of the wall and die
4. see that nothings there but your xp, o itmes, no gravestone

**Expected behavior**
There should have been a gravestoen

**Log files**
https://gist.github.com/Parciwal/7e6ffaec24a7d24d3ed4478410885789
this is a crah report, if you wat other logfiles, please state where to find them

**Versions**
1.16.5
1.16.5-forge-36.06.48
1.16.5-1.0.1

**Other mods**
create-mc1.16.5_v0.3.1
inventorypets-1.16.5-2.0.15
jei-1.16.5-7.7.0.106
replaymod-1.16.4-forge-1.0.0

**Comment by Parciwal** [comment]
after restarting the game, it works again

**Comment by henkelmax** [comment]
This error is caused by replaymod.

> after restarting the game, it works again

Alright. If it happens again try removing replaymod.
