### ISSUE TITLE
Grave not appearing inside oil

### ISSUE THREAD

**Issue by Rainbow0015** [henkelmax/gravestone#71]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I died inside of an oil deposit from buildcraft and the grave did not appear

**Steps to reproduce the issue**
1. Go to an oil deposit
2. drown in oil deposit
3. go back to the oil deposit

**Expected behavior**
I had expected to go back to find my grave or even my stuff like I had previously seen it do in water, but nothing.

**Versions**
- Minecraft version:1.12.2
- Forge version: 
- Mod version: gravestone-1.10.3.jar

**Other mods**
Actually Additions
Apple Trees Revived [Forge & Fabric][1.12.x - 1.17.1]
AppleSkin
Backpacks!
Base Metals
Biomes O' Plenty
Bookshelf
Buildcraft
Chance Cubes
ConnectedTexturesMod
CraftTweaker
Fast Leaf Decay
Game Stages
Gravity Gun
Hats
Hwyla
iChunUtil
Inventory Pets
Iron Chests
JourneyMap
Just Enough Items (JEI)
Just Enough Resources (JER)
Mantle
McHorse's McLib
Metamorph
MMD OreSpawn
MMDLib
Moar Tinkers
Morph
Neat
Oh The Biomes You'll Go
Ore Excavation
Patchouli
Portal Gun
ProjectE
ProjectE Integration
The Twilight Forest
Tinker I/O
Tinker's JEI
Tinkers Construct
Tinkers' Complement
Tinkers' Tool Leveling
TinkerStages
VeinMiner
Waila Harvestability
Waystones

**Comment by henkelmax** [comment]
Minecraft 1.12.2 is not supported anymore.
