### ISSUE TITLE
No data fixer registered for gravestone:player_ghost

### ISSUE THREAD

**Issue by xlive2233** [henkelmax/gravestone#75]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/gravestone/faq)!**
No data fixer registered for gravestone:player_ghos
[2021-10-16-1.log.gz](https://github.com/henkelmax/gravestone/files/7355100/2021-10-16-1.log.gz)
t

**Comment by 848244210** [comment]
e
