### ISSUE TITLE
I died multiple times, and to different mobs at the same time. Now I don't have my items.

### ISSUE THREAD

**Issue by Quidney** [henkelmax/gravestone#77]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
Here's a link to the issue I explained in full detail; https://www.reddit.com/r/feedthebeast/comments/r56ft7/oceanblock_gravestone_mod_items_disappearing/

**Steps to reproduce the issue**
Get killed by two mobs at the same time idk

**Expected behavior**
Get my items back when I break the grave.

**Log files**
https://gist.github.com/Quidney/d3dc14df61959e6e386527a000c45fa5

**Versions**
- Minecraft version; 1.16.5
- Forge version; 36.2.9
- Mod version 1.0.7

**Other mods**
Oceanblock modpack, 1.9.0

**Screenshots (Optional)**
![2021-11-29_22 33 11](https://user-images.githubusercontent.com/62697261/144216482-9582d1a2-5a92-414f-821d-1090f96cc6c9.png)

**Comment by henkelmax** [comment]
Did you get an obituary?

**Comment by Quidney** [comment]
> How can you die twice at the same time? That is not possible.
Fireballed by piglin. Both the ghast and piglin were attacking me at the same time and this death message occured

**Comment by Quidney** [comment]
Plus I had the obituary but after I broke my grave and didn't get the items back, I threw it in the lava.
And I don't care about those items but if this bug occurs again, I can't afford to lose my full set supremium armor and tool set.

**Comment by henkelmax** [comment]
This seems like an issue by another mod. This message is not possible in vanilla minecraft. If you throw away the obituary, your death ID gets lost. If you have the obituary, you can restore the items with a command.

**Comment by Quidney** [comment]
I don't wanna cheat though, even if its caused by a bug. Thanks for responding. I'll try and avoid dying in the nether

**Comment by henkelmax** [comment]
Please report this issue to the pack creator. If it happens again, please keep the obituary and report it to me. I will reopen this issue then.
