### ISSUE TITLE
Bug that crashes the game

### ISSUE THREAD

**Issue by Macroboot** [henkelmax/gravestone#79]
**Bug description**
When you die and want to take your objects from de gravestone, even if you just look at the graveston the game crashes, its in 1.17.1 version. 

**Expected behavior**
You should can just take your things and continue playing.

**Log files**
[crash-2021-12-08_15.27.43-server.txt](https://github.com/henkelmax/gravestone/files/7679171/crash-2021-12-08_15.27.43-server.txt)

**Versions**
- Minecraft 1.17.1
- Forge 1.17.1
- Mod is in its 1.17.1 version.

**Screenshots (Optional)**
![Uploading 2021-12-08 (1).png…]()

**Comment by henkelmax** [comment]
This is a bug of `WTHIT`. It can't handle mods that implement the Jade API.

**Comment by Macroboot** [comment]
What can I do to use the mod?

**Comment by henkelmax** [comment]
Remove WTHIT and install Jade instead.
Or report this to the WTHIT developers.
