### ISSUE TITLE
How to turn off oburitury

### ISSUE THREAD

**Issue by Mlg333** [henkelmax/gravestone#8]
Hi I would like to know how to turn off the oburitury because when I have to many it kicks me off my server, Thanks.

**Comment by henkelmax** [comment]
The option is called `enable_death_note` in the server config.

**Comment by Mlg333** [comment]
Sorry to bother again, but I use lan to play with my friends, so I don't have server config. Is there any way to turn it off on the mod itself?

**Comment by henkelmax** [comment]
There always is a server config. Please read the FAQ!

**Comment by Mlg333** [comment]
Ok sorry for the bother.
