### ISSUE TITLE
I died on the nether portal frame

### ISSUE THREAD

**Issue by dhs262003** [henkelmax/gravestone#82]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I died on the nether portal frame and when i tried to find my body/grave it didnt spawn

**Expected behavior**
i thought that the grave should have been spawned next to the frame

**Versions**
- Minecraft 1.18.1 Java
- 39.0.8
- [1.18.1] Gravestone Mod 1.18.1-1.0.0

**Other mods**
Sophisticated Backpacks

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/63971429/147344583-1d3b2741-a591-4acf-bcb1-b2413752ede7.png)
![image](https://user-images.githubusercontent.com/63971429/147344613-0e4cb782-6df8-41c7-9810-0923cfd75957.png)

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/147347377-bfd5a7a1-68fa-44f0-8433-c0878d2fe9e9.png)
