### ISSUE TITLE
Add gravestones to the dragon_immune tag

### ISSUE THREAD

**Issue by scmcgowen** [henkelmax/gravestone#83]
**Is your feature request related to a problem? Please describe.**
The Gravestone Mod is intended to keep your items safe. if it can be just deleted by the dragon, your items are not safe (even if they just pop out of the gravestone, that has a 5 minute timer)

**Describe the solution you'd like**
Quite simple, add gravestone:gravestone to the block tags of `minecraft:dragon_immune.`

**Describe alternatives you've considered**
I have made a datapack that fixes this problem by adding it to the `minecraft:dragon_immune` tag

**Comment by henkelmax** [comment]
Gravestones are indestructible without any tags. But yeah, for consistency and compatibility with other mods, I will add it.
