### ISSUE TITLE
Compass heading toward the grave when holding obituary

### ISSUE THREAD

**Issue by andrewminer** [henkelmax/gravestone#84]
**Is your feature request related to a problem? Please describe.**

I've included Gravestone in a vanilla-oriented modpack where we only use the vanilla Compass and Map for navigation (i.e., no JourneyMap, etc.).  However, without such extra mods, there's no way for players to find their graves except by pulling up the F3 screen and trying to find the coordinates listed on the obituary.

**Describe the solution you'd like**

I'd like players to be able to use the obituary like a compass which leads them to their gave.  It could:

* emit particles in the direction of the grave
* fly toward the grave when thrown like an ender pearl
* have a compass rose on it
* modify a compass to point to the grave when the two are crafted together

**Describe alternatives you've considered**

I *could* add JourneyMap (or something similar), but I'd prefer players use the vanilla map/compass.  I *could* add the DeathCompass mod, but it crashes my server.  I *could* listen to players whine about having to use the F3 screen, but I'd *really* rather not.  ;-)

**Additional context**

I vaguely recall either this or a nearly identical mod used to have the obituary emit particles toward the grave when held in the player's hand.  That would completely solve the problem for me.

**Comment by henkelmax** [comment]
I guess this is now obsolete with 1.19
