### ISSUE TITLE
Item's disappear on death from time to time.

### ISSUE THREAD

**Issue by ZombieOw** [henkelmax/gravestone#93]
**Bug description**
When ever I die to anything, Mob or other it will drop my gravestone, When I go to the location of the gravestone and mine it, it breaks and none of my stuff comes out of it. I am thinking it's doing this because of the traveler's backpack mod because the backpacks also get placed on the ground on death but I'm not sure. Any fix for this would be greatly appreciated. 

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.34
- Mod version: 1.0.7

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

-Traveler's backpack - I think this may be the issue to the bug but I'm not sure.

-Ice and Fire - I've died to mainly these mobs when the bug occurs.

**Comment by henkelmax** [comment]
Please provide log files

**Comment by henkelmax** [comment]
And I'm pretty sure its related to this: https://github.com/Alex-the-666/Ice_and_Fire/issues/3019

**Comment by henkelmax** [comment]
Closed due to inactivity
