### ISSUE TITLE
Compatibility with Player Tabs mod

### ISSUE THREAD

**Issue by Reisanji** [henkelmax/gravestone#94]
**Bug description**
When using [Player Tabs](https://www.curseforge.com/minecraft/mc-mods/player-tabs) upon death inactive tabs get dropped into the world.

**Steps to reproduce the issue**
1. Die

**Expected behavior**
Have the Grave Stone collect all tabs.

**Log files**
[latest.log](https://github.com/henkelmax/gravestone/files/8653862/latest.log)

**Versions**
- Minecraft 1.18.2
- Forge 40.1.2
- Player Tabs 1.0
- GraveStone 1.0.2

**Screenshots (Optional)**
![Middle Tab](https://user-images.githubusercontent.com/53265963/167464030-b2e62568-8e79-416f-9b99-9cfb6294de81.png)
![Midle Tab Death Note](https://user-images.githubusercontent.com/53265963/167464034-58a2d587-2fe3-4e99-aff4-fc6adf9ad37e.png)
![Right Tab Death Note](https://user-images.githubusercontent.com/53265963/167464036-a59269d5-f7ba-4be9-814f-fdb74ced0406.png)
![Right Tab](https://user-images.githubusercontent.com/53265963/167464042-46d1b819-804b-404f-90d9-8c2550ad348d.png)

**Comment by henkelmax** [comment]
This is a player tabs issue then. The gravestone mod only stores items that actually get dropped on death with forges death event.
