### ISSUE TITLE
[Bug] If you die near an ocean monument, your grave becomes unbreakable as well

### ISSUE THREAD

**Issue by Kadamitas** [henkelmax/gravestone#96]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**If you venture to an ocean monument and did not kill the elder guardian, your grave also becomes unbreakable.**

**Steps to reproduce the issue**
1. Go to Ocean Monument
2. Die
3. Try to break grave
4. Can't.

**Expected behavior**
Be able to break your grave.

**Versions**
- Minecraft version: 1.18.2
- Forge version: 40.1.47
- Mod version: 1.0.2

**Other mods**
Direwolf20 1.18

**Comment by henkelmax** [comment]
You can enable the sneak pickup feature in the config or just drink a milk bucket right before breaking it.
