### ISSUE TITLE
Re-equip Baubles

### ISSUE THREAD

**Issue by JustJinxed** [henkelmax/gravestone#98]
**Is your feature request related to a problem? Please describe.**
More of a quality of life than a problem. Having to re-equip baubles is tedious and very difficult if there's mobs on top of your grave

**Describe the solution you'd like**
Upon death, record the location of bauble items and store it in grave data, and upon retrieving your gravestone, sort the bauble items back into their bauble slots.

**Describe alternatives you've considered**
Enigmatic Graves was the first grave mod I found that works pretty seamlessly with baubles.(https://www.curseforge.com/minecraft/mc-mods/enigmatic-graves) 

**Additional context**
https://youtu.be/SJBgj3qkUqs?t=1941
Just an example of what we're having to do manually every time we go to get our gravestone

**Comment by henkelmax** [comment]
https://github.com/henkelmax/gravestone/issues/37#issuecomment-772537411
